import test from 'node:test';
import assert from 'node:assert/strict';
import {youtubeId,locationInput,editContent,safeLink} from '../server/content.mjs';
import handler from '../api/site.js';
const id='8ec30f36-4dda-4d97-9cd1-8250a62d4a2c';
test('YouTube editor accepts watch, shared, Shorts and live links',()=>{for(const u of ['https://www.youtube.com/watch?v=7QLze6D0ODY&t=20','https://youtu.be/7QLze6D0ODY?si=test','https://youtube.com/shorts/7QLze6D0ODY','https://youtube.com/live/7QLze6D0ODY'])assert.equal(youtubeId(u),'7QLze6D0ODY');});
test('YouTube and destination URLs reject spoofed hosts and executable links',()=>{for(const u of ['javascript:alert(1)','https://youtube.com.evil.test/watch?v=7QLze6D0ODY','https://youtu.be/short','https://user:pass@youtube.com/watch?v=7QLze6D0ODY'])assert.throws(()=>youtubeId(u));for(const u of ['javascript:alert(1)','http://example.com','https://user:pass@example.com','https://127.0.0.1/a'])assert.throws(()=>safeLink(u));assert.equal(safeLink('https://kick.com/zeekfusion'),'https://kick.com/zeekfusion');});
test('Map edits use validated country/state choices and optional stops',()=>{const x=locationInput({id,scope:'usa',placeId:'12',location:'Miami',status:'visited',video:'https://kick.com/zeekfusion'});assert.equal(x.name,'Florida');assert.equal(x.location,'Miami');assert.throws(()=>locationInput({...x,placeId:'99'}));assert.throws(()=>locationInput({...x,status:'anything'}));});
test('Content edits preserve other sections and update/delete the exact location',()=>{const start={latestVideo:{id:'7QLze6D0ODY',title:'Current'},locations:[]};const next=editContent(start,{revision:0,action:'location',location:{id,scope:'world',placeId:'Austria',status:'upcoming'}});assert.equal(start.locations.length,0);assert.equal(next.latestVideo.title,'Current');assert.equal(next.locations.length,1);assert.equal(editContent(next,{revision:1,action:'delete',id}).locations.length,0);assert.throws(()=>editContent(next,{revision:-1,action:'delete',id}));});
function res(){return {code:200,setHeader(){},status(x){this.code=x;return this;},json(x){this.body=x;return this;},end(){return this;}};}
test('Content editor blocks anonymous access and cross-origin writes',async()=>{for(const [method,query,headers,status] of [['GET',{admin:'1'},{},401],['POST',{}, {origin:'https://bad.example'},403],['POST',{}, {origin:'https://www.zeekfusion.com'},401]]){const r=res();await handler({method,query,headers,body:{}},r);assert.equal(r.code,status);}});
test('Authenticated non-owner cannot edit or view creator content controls',async()=>{const saved=global.fetch;process.env.SUPABASE_URL='https://db.test';process.env.SUPABASE_SECRET_KEY='test';global.fetch=async url=>new Response(JSON.stringify(String(url).includes('/rpc/z_rate_limit')?true:[{kick_user_id:99,username:'visitor'}]),{status:200});try{const r=res();await handler({method:'GET',query:{admin:'1'},headers:{cookie:'z_session='+ 'a'.repeat(43)}},r);assert.equal(r.code,403);}finally{global.fetch=saved;}});
test('Live status uses a fresh server observation and never exposes runtime internals',async()=>{const original=global.fetch;process.env.SUPABASE_URL='https://db.test';process.env.SUPABASE_SECRET_KEY='test';global.fetch=async url=>new Response(JSON.stringify(String(url).includes('/rpc/z_rate_limit')?true:[{is_live:false,checked_at:new Date().toISOString()}]));try{const r=res();await handler({method:'GET',query:{live:'1'},headers:{}},r);assert.equal(r.code,200);assert.equal(r.body.status,'offline');assert.deepEqual(Object.keys(r.body).sort(),['checkedAt','status']);}finally{global.fetch=original;}});
test('Stale stream status is unknown when another refresh is in progress',async()=>{const original=global.fetch;global.fetch=async url=>new Response(JSON.stringify(String(url).includes('/rpc/z_rate_limit')?true:String(url).includes('/rpc/z_lock')?false:[{is_live:false,checked_at:'2020-01-01T00:00:00Z'}]));try{const r=res();await handler({method:'GET',query:{live:'1'},headers:{}},r);assert.equal(r.body.status,'unknown');}finally{global.fetch=original;}});
