import test from 'node:test';
import assert from 'node:assert/strict';
import {rewardInput,uploadInput,overlayToken,verifyOverlayToken,publicKey} from '../server/rewards.mjs';
import {createAlertQueue} from '../components/alert-queue.mjs';
import handler from '../api/reward-alerts.js';
const reward={title:'Freeze',command_name:'freeze',description:'Hold still',cost:1,stock:null,enabled:true};
test('Reward settings validate stock, currency, cooldown, duration and safe media URLs',()=>{
 assert.equal(rewardInput(reward).alert_duration,8);assert.equal(rewardInput({...reward,cost:1.01}).cost,1.01);
 for(const fields of [{cost:0},{cost:-1},{cost:1.005},{stock:-1},{stock:1.5},{alert_duration:0},{alert_duration:121},{alert_volume:101},{cooldown_seconds:-1},{cooldown_seconds:.2},{image_url:'javascript:alert(1)'},{audio_url:'http://localhost/a.mp3'}])assert.throws(()=>rewardInput({...reward,...fields}));
 assert.equal(rewardInput({...reward,thumbnail_url:'https://example.com/a.gif'}).thumbnail_url,'https://example.com/a.gif');
});
test('Uploads allow only supported media within limits, never caller-controlled paths',()=>{assert.match(uploadInput({type:'audio/mpeg',size:100,path:'../secret'}).path,/^[a-f\d-]+\.mp3$/);for(const b of [{type:'image/svg+xml',size:10},{type:'text/html',size:100},{type:'image/png',size:11000000},{type:'audio/mpeg',size:22000000},{type:'image/png',size:0}])assert.throws(()=>uploadInput(b));});
test('Overlay capability is secret-bound, nonce-bound, and cannot expose service keys',()=>{process.env.KICK_CLIENT_SECRET='test-secret';const t=overlayToken('one');assert(verifyOverlayToken(t,'one'));assert(!verifyOverlayToken(t,'two'));assert(!verifyOverlayToken(t+'x','one'));assert.equal(publicKey('sb_secret_abc'),null);const key=role=>'x.'+Buffer.from(JSON.stringify({role})).toString('base64url')+'.y';assert.equal(publicKey(key('service_role')),null);assert.equal(publicKey(key('anon')),key('anon'));});
test('Overlay owner endpoints require login; mutations reject cross-site requests',async()=>{const run=async req=>{const res={status(n){this.code=n;return this},setHeader(){},json(x){this.body=x;return this},end(){}};await handler(req,res);return res;};assert.equal((await run({method:'GET',query:{owner:'1'},headers:{}})).code,401);assert.equal((await run({method:'POST',query:{owner:'1'},headers:{origin:'https://evil.example'},body:{action:'upload'}})).code,403);});
test('Queue serializes bursts and acknowledges each item only after playback finishes',async()=>{const events=[],items=[{id:'a'},{id:'b'}];let release,playing=0;const q=createAlertQueue({request:async b=>{events.push(b.action+(b.id||''));return b.action==='claim'?{alert:items.shift()||null}:{ok:true}},play:async a=>{assert.equal(playing++,0);events.push('play'+a.id);if(a.id==='a')await new Promise(r=>release=r);playing--;return true}});const first=q.wake();await new Promise(r=>setImmediate(r));q.wake();q.wake();assert.deepEqual(events,['claim','playa']);release();await first;assert.deepEqual(events,['claim','playa','finisha','claim','playb','finishb','claim']);q.stop();});
test('A lost acknowledgement retries the claim without replaying the same alert',async()=>{const seen=new Set();let plays=0,acks=0,retry;const q=createAlertQueue({schedule:fn=>{retry=fn;return 1},cancel(){},remember:id=>seen.add(id),wasPlayed:id=>seen.has(id),play:async()=>{plays++;return true},request:async b=>{if(b.action==='claim')return {alert:acks<2?{id:'a'}:null};if(++acks===1)throw Error('Network');return {ok:true}}});await q.wake();await retry();await new Promise(r=>setImmediate(r));assert.equal(plays,1);assert.equal(acks,2);q.stop();});
test('A busy second overlay waits for the active lease and an idle queue does not poll',async()=>{let calls=0,delay;const q=createAlertQueue({request:async()=>{calls++;return calls===1?{retryAfter:12}:{alert:null}},play:async()=>{throw Error('Unexpected playback')},schedule:(fn,ms)=>{delay=ms;return 1},cancel(){}});await q.wake();assert.equal(delay,12000);await q.wake();assert.equal(calls,2);q.stop();});
test('Signed-in viewers cannot upload media, read owner links, or rotate overlay access',async()=>{const old=globalThis.fetch;process.env.SUPABASE_URL='https://db.example';process.env.SUPABASE_SECRET_KEY='test';const paths=[];globalThis.fetch=async url=>{paths.push(url);return {ok:true,text:async()=>url.includes('z_rate_limit')?'true':JSON.stringify([{kick_user_id:12,username:'ZeekFusion'}])}};try{for(const action of [null,'upload','rotate']){const res={status(n){this.code=n;return this},setHeader(){},json(x){this.body=x;return this},end(){}};await handler({method:action?'POST':'GET',query:{owner:'1'},headers:{origin:'https://www.zeekfusion.com',cookie:'z_session='+'a'.repeat(43)},body:{action}},res);assert.equal(res.code,403);}assert(!paths.some(x=>x.includes('z_overlay_settings')||x.includes('/storage/')));}finally{globalThis.fetch=old;}});
test('Forged overlay keys cannot claim or finish queued alerts',async()=>{const old=globalThis.fetch;const paths=[];globalThis.fetch=async url=>{paths.push(url);return {ok:true,text:async()=>url.includes('z_rate_limit')?'true':JSON.stringify([{nonce:'nonce'}])}};try{const res={status(n){this.code=n;return this},setHeader(){},json(x){this.body=x;return this},end(){}};await handler({method:'POST',query:{},headers:{origin:'https://www.zeekfusion.com',authorization:'Bearer '+'a'.repeat(43)},body:{action:'claim',client:'11111111-1111-1111-1111-111111111111'}},res);assert.equal(res.code,401);assert(!paths.some(x=>x.includes('z_claim_alert')||x.includes('z_finish_alert')));}finally{globalThis.fetch=old;}});

test('Reward command is independent, normalized and validated',()=>{assert.equal(rewardInput({...reward,title:'Hydrate',command_name:'  drink water  '}).command_name,'drink water');assert.equal(rewardInput({...reward,command_name:'LOUD Sound'}).command_name,'loud sound');for(const command_name of ['',null,undefined,'x'.repeat(81),'a\nb','!buy hydrate'])assert.throws(()=>rewardInput({...reward,command_name}));});
