begin;
-- Preserve all existing balances and ledger entries, while allowing fractional Zs.
alter table public.z_users alter column zs_balance type numeric(18,2), alter column lifetime_zs type numeric(18,2);
alter table public.z_transactions alter column amount type numeric(18,2);
create table if not exists public.z_config(id integer primary key check(id=1),settings jsonb not null);
insert into public.z_config values(1,'{"subscription_z":5,"gift_z":5,"renewal_z":5,"question_z":1,"question_interval_minutes":30,"answer_seconds":60,"questions_enabled":true,"kicks_enabled":false,"kicks_per_z":100,"botrix_enabled":false,"botrix_points_per_z":1000,"botrix_weekly_cap_z":5}') on conflict do nothing;
create table if not exists public.z_runtime(id integer primary key check(id=1),is_live boolean not null default false,next_question_at timestamptz,checked_at timestamptz,bot_error text,last_webhook_at timestamptz);
insert into public.z_runtime(id) values(1) on conflict do nothing;
create table if not exists public.z_sessions(token_hash text primary key,kick_user_id bigint not null,username text not null,expires_at timestamptz not null);
create table if not exists public.z_bot(id integer primary key check(id=1),encrypted_tokens text not null,updated_at timestamptz default now());
create table if not exists public.z_locks(name text primary key,owner uuid not null,expires_at timestamptz not null);
create table if not exists public.z_tick_tokens(token uuid primary key default gen_random_uuid(),expires_at timestamptz not null default now()+interval '2 minutes');
create table if not exists public.z_questions(id bigint generated by default as identity primary key,question text not null unique,answers text[] not null,category text not null default 'General',enabled boolean not null default true,last_used_at timestamptz);
create table if not exists public.z_rounds(id uuid primary key default gen_random_uuid(),question_id bigint references public.z_questions,question text not null,answers text[] not null,reward numeric(18,2) not null,status text not null default 'pending' check(status in('pending','open','won','expired','cancelled')),opened_at timestamptz,expires_at timestamptz,winner_id bigint,winner_username text,created_at timestamptz default now());
create unique index if not exists z_one_active_round on public.z_rounds((true)) where status in('pending','open');
create table if not exists public.z_outbox(id uuid primary key default gen_random_uuid(),dedupe text unique not null,content text not null,round_id uuid references public.z_rounds,status text not null default 'pending',attempts integer not null default 0,created_at timestamptz default now(),sent_at timestamptz);
create table if not exists public.z_rewards(id uuid primary key default gen_random_uuid(),title text not null,description text not null default '',cost numeric(18,2) not null check(cost>0),stock integer check(stock>=0),enabled boolean not null default false,created_at timestamptz default now());
create table if not exists public.z_redemptions(id uuid primary key,kick_user_id bigint not null references public.z_users, reward_id uuid not null references public.z_rewards,title text not null,cost numeric(18,2) not null,status text not null default 'pending' check(status in('pending','fulfilled','refunded')),created_at timestamptz default now());
create table if not exists public.z_conversion_tickets(id uuid primary key,kick_user_id bigint not null references public.z_users,points integer not null check(points>0),zs numeric(18,2) not null check(zs>0),status text not null default 'pending' check(status in('pending','approved','rejected')),proof text,created_at timestamptz default now(),resolved_at timestamptz);
create unique index if not exists z_one_pending_conversion on public.z_conversion_tickets(kick_user_id) where status='pending';
create table if not exists public.z_admin_log(id bigint generated always as identity primary key,actor bigint not null,action text not null,details jsonb not null default '{}',created_at timestamptz default now());
create table if not exists public.z_command_limits(kick_user_id bigint primary key,last_at timestamptz not null default now());
-- Every Z table is server-only. Public views are returned through curated endpoints.
do $$declare t record;begin for t in select tablename from pg_tables where schemaname='public' and tablename like 'z\_%' escape '\' loop execute format('alter table public.%I enable row level security',t.tablename);execute format('revoke all on public.%I from anon, authenticated',t.tablename);execute format('grant all on public.%I to service_role',t.tablename);end loop;end$$;
create or replace function public.z_award(p_user bigint,p_name text,p_amount numeric,p_reason text,p_event text,p_metadata jsonb default '{}') returns jsonb language plpgsql security definer set search_path=public as $$
declare tx bigint;u public.z_users;begin
 if p_user<=0 or p_name is null or length(p_name)>100 or p_amount=0 or abs(p_amount)>1000000 or p_amount<>round(p_amount,2) or p_event is null then raise exception 'Invalid award';end if;
 insert into z_users(kick_user_id,username) values(p_user,p_name) on conflict(kick_user_id) do update set username=excluded.username;
 select * into u from z_users where kick_user_id=p_user for update;
 if exists(select 1 from z_transactions where kick_event_id=p_event) then return jsonb_build_object('awarded',false,'balance',u.zs_balance);end if;
 if u.zs_balance+p_amount<0 then raise exception 'Insufficient Zs';end if;
 insert into z_transactions(kick_user_id,amount,reason,kick_event_id,metadata) values(p_user,p_amount,p_reason,p_event,p_metadata) on conflict(kick_event_id) do nothing returning id into tx;
 if tx is null then return jsonb_build_object('awarded',false,'balance',u.zs_balance);end if;
 update z_users set zs_balance=zs_balance+p_amount,lifetime_zs=lifetime_zs+greatest(p_amount,0),updated_at=now() where kick_user_id=p_user returning * into u;
 return jsonb_build_object('awarded',true,'balance',u.zs_balance);end$$;
create or replace function public.z_lock(p_name text,p_owner uuid,p_seconds integer default 45) returns boolean language plpgsql security definer set search_path=public as $$begin
 insert into z_locks values(p_name,p_owner,now()+make_interval(secs=>p_seconds)) on conflict(name) do update set owner=excluded.owner,expires_at=excluded.expires_at where z_locks.expires_at<now();
 return exists(select 1 from z_locks where name=p_name and owner=p_owner);end$$;
create or replace function public.z_unlock(p_name text,p_owner uuid) returns void language sql security definer set search_path=public as $$delete from z_locks where name=p_name and owner=p_owner$$;
create or replace function public.z_consume_tick(p_token uuid) returns boolean language plpgsql security definer set search_path=public as $$declare t uuid;begin delete from z_tick_tokens where token=p_token and expires_at>now() returning token into t;return t is not null;end$$;
create or replace function public.z_start_round() returns uuid language plpgsql security definer set search_path=public as $$
declare c jsonb;r z_runtime;q z_questions;n uuid;begin
 perform pg_advisory_xact_lock(20306616,1);
 select settings into c from z_config where id=1;select * into r from z_runtime where id=1 for update;
 update z_rounds set status='expired' where status='open' and expires_at<now();
 update z_rounds set status='cancelled' where status='pending' and created_at<now()-interval '5 minutes';
 if not r.is_live or not (c->>'questions_enabled')::boolean or r.next_question_at>now() or exists(select 1 from z_rounds where status in('pending','open')) then return null;end if;
 select * into q from z_questions where enabled order by last_used_at nulls first,random() limit 1;
 if q.id is null then return null;end if;
 insert into z_rounds(question_id,question,answers,reward) values(q.id,q.question,q.answers,(c->>'question_z')::numeric) returning id into n;
 update z_questions set last_used_at=now() where id=q.id;
 insert into z_outbox(dedupe,content,round_id) values('question:'||n,'⚡ Z QUESTION: '||q.question||' | First correct answer wins '||(c->>'question_z')||' Zs. You have '||(c->>'answer_seconds')||' seconds!',n);
 update z_runtime set next_question_at=now()+make_interval(mins=>(c->>'question_interval_minutes')::integer) where id=1;
 return n;end$$;
create or replace function public.z_open_round(p_round uuid) returns void language plpgsql security definer set search_path=public as $$declare secs integer;begin
 select (settings->>'answer_seconds')::integer into secs from z_config where id=1;
 update z_rounds set status='open',opened_at=now(),expires_at=now()+make_interval(secs=>secs) where id=p_round and status='pending';end$$;
create or replace function public.z_answer(p_user bigint,p_name text,p_answer text,p_message text,p_created timestamptz) returns jsonb language plpgsql security definer set search_path=public as $$
declare r z_rounds;result jsonb;begin
 select * into r from z_rounds where status='open' order by created_at desc limit 1 for update;
 if r.id is null or r.expires_at<now() or p_created<r.opened_at or p_created>r.expires_at or not(p_answer=any(r.answers)) or p_user=20306616 then return null;end if;
 update z_rounds set status='won',winner_id=p_user,winner_username=p_name where id=r.id;
 if r.reward>0 then result:=z_award(p_user,p_name,r.reward,'Z Question winner','question:'||r.id,jsonb_build_object('message_id',p_message));end if;
 insert into z_outbox(dedupe,content) values('winner:'||r.id,'🏆 @'||p_name||' got it! +'||r.reward||' Zs. Your balance: '||coalesce(result->>'balance','0')||' Zs.');
 return jsonb_build_object('won',true,'reward',r.reward);end$$;
create or replace function public.z_balance_command(p_user bigint,p_name text,p_message text) returns void language plpgsql security definer set search_path=public as $$declare b numeric;ok bigint;begin
 insert into z_command_limits values(p_user,now()) on conflict(kick_user_id) do update set last_at=now() where z_command_limits.last_at<now()-interval '30 seconds' returning kick_user_id into ok;
 if ok is null then return;end if;
 select zs_balance into b from z_users where kick_user_id=p_user;
 insert into z_outbox(dedupe,content) values('command:'||p_message,'⚡ @'||p_name||' — '||coalesce(b,0)||' Zs. Visit zeekfusion.com/#/vault') on conflict(dedupe) do nothing;end$$;
create or replace function public.z_redeem(p_user bigint,p_name text,p_reward uuid,p_request uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r z_rewards;x z_redemptions;begin
 perform pg_advisory_xact_lock(hashtextextended(p_request::text,0));
 select * into x from z_redemptions where id=p_request;
 if x.id is not null then if x.kick_user_id<>p_user then raise exception 'Invalid request';end if;return to_jsonb(x);end if;
 select * into r from z_rewards where id=p_reward for update;
 if r.id is null or not r.enabled or r.stock=0 then raise exception 'Reward unavailable';end if;
 perform z_award(p_user,p_name,-r.cost,'Redeemed: '||r.title,'redeem:'||p_request);
 insert into z_redemptions(id,kick_user_id,reward_id,title,cost) values(p_request,p_user,r.id,r.title,r.cost) returning * into x;
 update z_rewards set stock=stock-1 where id=r.id and stock is not null;return to_jsonb(x);end$$;
create or replace function public.z_resolve_redemption(p_id uuid,p_status text,p_actor bigint) returns void language plpgsql security definer set search_path=public as $$declare r z_redemptions;n text;begin
 if p_actor<>20306616 or p_status not in('fulfilled','refunded') then raise exception 'Unauthorized';end if;
 select * into r from z_redemptions where id=p_id for update;
 if r.id is null or r.status<>'pending' then return;end if;
 if p_status='refunded' then select username into n from z_users where kick_user_id=r.kick_user_id;perform z_award(r.kick_user_id,n,r.cost,'Reward refund','refund:'||r.id);update z_rewards set stock=stock+1 where id=r.reward_id and stock is not null;end if;
 update z_redemptions set status=p_status where id=p_id;
 insert into z_admin_log(actor,action,details) values(p_actor,'redemption_'||p_status,jsonb_build_object('id',p_id));end$$;
create or replace function public.z_conversion(p_user bigint,p_name text,p_points integer,p_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare c jsonb;amount numeric;used numeric;x z_conversion_tickets;begin
 perform pg_advisory_xact_lock(p_user);
 select * into x from z_conversion_tickets where id=p_id;if x.id is not null then if x.kick_user_id<>p_user then raise exception 'Invalid request';end if;return to_jsonb(x);end if;
 select settings into c from z_config where id=1;
 if not(c->>'botrix_enabled')::boolean or p_points<=0 or p_points%(c->>'botrix_points_per_z')::integer<>0 then raise exception 'Conversions unavailable or invalid amount';end if;
 amount:=p_points/(c->>'botrix_points_per_z')::numeric;
 select coalesce(sum(zs),0) into used from z_conversion_tickets where kick_user_id=p_user and status in('pending','approved') and created_at>=date_trunc('week',now());
 if used+amount>(c->>'botrix_weekly_cap_z')::numeric then raise exception 'Weekly conversion limit exceeded';end if;
 insert into z_users(kick_user_id,username) values(p_user,p_name) on conflict(kick_user_id) do nothing;
 insert into z_conversion_tickets(id,kick_user_id,points,zs) values(p_id,p_user,p_points,amount) returning * into x;return to_jsonb(x);end$$;
create or replace function public.z_resolve_conversion(p_id uuid,p_status text,p_proof text,p_actor bigint) returns void language plpgsql security definer set search_path=public as $$declare t z_conversion_tickets;n text;begin
 if p_actor<>20306616 or p_status not in('approved','rejected') then raise exception 'Unauthorized';end if;
 select * into t from z_conversion_tickets where id=p_id for update;if t.id is null or t.status<>'pending' then return;end if;
 if p_status='approved' then if length(trim(coalesce(p_proof,'')))<5 then raise exception 'Record proof that BotRix points were deducted';end if;select username into n from z_users where kick_user_id=t.kick_user_id;perform z_award(t.kick_user_id,n,t.zs,'BotRix conversion','conversion:'||t.id);end if;
 update z_conversion_tickets set status=p_status,proof=p_proof,resolved_at=now() where id=p_id;
 insert into z_admin_log(actor,action,details) values(p_actor,'conversion_'||p_status,jsonb_build_object('id',p_id));end$$;
-- Close public access to all award/administrative functions, including the legacy function.
do $$declare f record;begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (p.proname like 'z\_%' escape '\' or p.proname='award_z') loop execute format('revoke all on function %s from public, anon, authenticated',f.signature);execute format('grant execute on function %s to service_role',f.signature);end loop;end$$;
notify pgrst,'reload schema';
commit;
