begin;
insert into public.z_questions(question,answers,category) values
('Which city is the capital of Austria?',ARRAY['vienna','wien'],'Travel'),
('Which city is the capital of Italy?',ARRAY['rome','roma'],'Travel'),
('Which country is home to Barcelona?',ARRAY['spain'],'Travel'),
('Which river runs through London?',ARRAY['thames','river thames','the thames'],'Travel'),
('Which country is home to Kyoto?',ARRAY['japan'],'Travel'),
('What is the currency of Japan?',ARRAY['yen','japanese yen'],'Travel'),
('Which Italian city is famous for gondolas?',ARRAY['venice','venezia'],'Travel'),
('Which country is home to the Taj Mahal?',ARRAY['india'],'Travel'),
('Which continent is Brazil in?',ARRAY['south america'],'Travel'),
('Which city is known as the Big Apple?',ARRAY['new york','new york city','nyc'],'Travel'),
('Which ocean lies between Europe and North America?',ARRAY['atlantic','atlantic ocean','the atlantic'],'Travel'),
('Which city is the capital of France?',ARRAY['paris'],'Travel'),
('Which country is home to the Great Pyramid of Giza?',ARRAY['egypt'],'Travel'),
('Which city is the capital of Greece?',ARRAY['athens'],'Travel'),
('Which country is home to Machu Picchu?',ARRAY['peru'],'Travel'),
('Which city is the capital of Portugal?',ARRAY['lisbon','lisboa'],'Travel'),
('Which city is the capital of South Korea?',ARRAY['seoul'],'Travel'),
('Which city is the capital of Australia?',ARRAY['canberra'],'Travel'),
('Which country is home to Mount Fuji?',ARRAY['japan'],'Travel'),
('Which country is home to Dubrovnik?',ARRAY['croatia'],'Travel'),
('How many sides does a hexagon have?',ARRAY['6','six'],'Quick thinking'),
('What is 12 multiplied by 8?',ARRAY['96','ninety six'],'Quick thinking'),
('How many minutes are in two hours?',ARRAY['120','one hundred twenty','one hundred and twenty'],'Quick thinking'),
('How many sides does a triangle have?',ARRAY['3','three'],'Quick thinking'),
('What is the square root of 81?',ARRAY['9','nine'],'Quick thinking'),
('What is 15 percent of 100?',ARRAY['15','fifteen'],'Quick thinking'),
('How many degrees are in a right angle?',ARRAY['90','ninety'],'Quick thinking'),
('What is 7 multiplied by 9?',ARRAY['63','sixty three'],'Quick thinking'),
('How many months have exactly 30 days?',ARRAY['4','four'],'Quick thinking'),
('How many hours are in three days?',ARRAY['72','seventy two'],'Quick thinking'),
('Which planet is closest to the Sun?',ARRAY['mercury'],'Science'),
('Which planet is known as the Red Planet?',ARRAY['mars'],'Science'),
('What gas do plants absorb during photosynthesis?',ARRAY['carbon dioxide','co2'],'Science'),
('What is the chemical symbol for gold?',ARRAY['au'],'Science'),
('How many legs does an adult insect have?',ARRAY['6','six'],'Science'),
('What is the largest planet in our solar system?',ARRAY['jupiter'],'Science'),
('What force keeps us on the ground?',ARRAY['gravity'],'Science'),
('What is water called in its solid state?',ARRAY['ice'],'Science'),
('What part of a plant absorbs water from the soil?',ARRAY['roots','root','the roots'],'Science'),
('Which organ pumps blood around the human body?',ARRAY['heart','the heart'],'Science'),
('What is the main ingredient in guacamole?',ARRAY['avocado','avocados'],'Food'),
('Which fruit is dried to make raisins?',ARRAY['grape','grapes'],'Food'),
('What is the main ingredient in traditional hummus?',ARRAY['chickpeas','chickpea','garbanzo beans'],'Food'),
('Which country is traditionally associated with sushi?',ARRAY['japan'],'Food'),
('Which nut is used in traditional marzipan?',ARRAY['almond','almonds'],'Food'),
('What is the main ingredient in tofu?',ARRAY['soybeans','soybean','soy beans','soya beans','soy'],'Food'),
('Which fruit is used to make traditional cider?',ARRAY['apple','apples'],'Food'),
('What kind of pasta is shaped like little tubes?',ARRAY['penne'],'Food'),
('Which vegetable is used in traditional sauerkraut?',ARRAY['cabbage'],'Food'),
('Which spice gives saffron rice its yellow color?',ARRAY['saffron'],'Food'),
('What is the name of the cowboy in Toy Story?',ARRAY['woody'],'Pop culture'),
('What is the name of Mario''s brother?',ARRAY['luigi'],'Games'),
('In Minecraft, what green creature explodes near players?',ARRAY['creeper','a creeper'],'Games'),
('Which game series features Pikachu?',ARRAY['pokemon'],'Games'),
('What color do blue and yellow paint make when mixed?',ARRAY['green'],'General'),
('How many strings does a standard guitar have?',ARRAY['6','six'],'Music'),
('Which chess piece moves in an L shape?',ARRAY['knight','the knight'],'Games'),
('In tennis, what word means a score of zero?',ARRAY['love'],'Sports'),
('How many players does one soccer team have on the field at kickoff?',ARRAY['11','eleven'],'Sports'),
('What is the largest living animal?',ARRAY['blue whale','the blue whale'],'Nature')
on conflict(question) do nothing;
commit;
