begin;
create table if not exists public.z_travel_destinations(kind text not null check(kind in ('states','countries')),place text not null,primary key(kind,place));
create table if not exists public.z_travel_voters(id uuid primary key default gen_random_uuid());
create table if not exists public.z_travel_identities(identity text primary key,voter uuid not null references public.z_travel_voters(id));
create table if not exists public.z_travel_votes(id uuid primary key,voter uuid not null references public.z_travel_voters(id),kind text not null,place text not null,created_at timestamptz not null default now(),foreign key(kind,place) references public.z_travel_destinations(kind,place));
create index if not exists z_travel_votes_voter on public.z_travel_votes(voter);
create index if not exists z_travel_identities_voter on public.z_travel_identities(voter);
alter table public.z_travel_destinations enable row level security;
alter table public.z_travel_voters enable row level security;
alter table public.z_travel_identities enable row level security;
alter table public.z_travel_votes enable row level security;
revoke all on public.z_travel_destinations,public.z_travel_voters,public.z_travel_identities,public.z_travel_votes from public,anon,authenticated;
insert into public.z_travel_destinations(kind,place) values
('countries','Afghanistan'),
('countries','Albania'),
('countries','Algeria'),
('countries','Angola'),
('countries','Argentina'),
('countries','Armenia'),
('countries','Australia'),
('countries','Austria'),
('countries','Azerbaijan'),
('countries','Bahamas'),
('countries','Bangladesh'),
('countries','Belarus'),
('countries','Belgium'),
('countries','Belize'),
('countries','Benin'),
('countries','Bhutan'),
('countries','Bolivia'),
('countries','Bosnia and Herz.'),
('countries','Botswana'),
('countries','Brazil'),
('countries','Brunei'),
('countries','Bulgaria'),
('countries','Burkina Faso'),
('countries','Burundi'),
('countries','Cambodia'),
('countries','Cameroon'),
('countries','Canada'),
('countries','Central African Rep.'),
('countries','Chad'),
('countries','Chile'),
('countries','China'),
('countries','Colombia'),
('countries','Congo'),
('countries','Costa Rica'),
('countries','Croatia'),
('countries','Cuba'),
('countries','Cyprus'),
('countries','Czechia'),
('countries','Côte d''Ivoire'),
('countries','Dem. Rep. Congo'),
('countries','Denmark'),
('countries','Djibouti'),
('countries','Dominican Rep.'),
('countries','Ecuador'),
('countries','Egypt'),
('countries','El Salvador'),
('countries','Eq. Guinea'),
('countries','Eritrea'),
('countries','Estonia'),
('countries','Ethiopia'),
('countries','Falkland Is.'),
('countries','Fiji'),
('countries','Finland'),
('countries','Fr. S. Antarctic Lands'),
('countries','France'),
('countries','Gabon'),
('countries','Gambia'),
('countries','Georgia'),
('countries','Germany'),
('countries','Ghana'),
('countries','Greece'),
('countries','Greenland'),
('countries','Guatemala'),
('countries','Guinea'),
('countries','Guinea-Bissau'),
('countries','Guyana'),
('countries','Haiti'),
('countries','Honduras'),
('countries','Hungary'),
('countries','Iceland'),
('countries','India'),
('countries','Indonesia'),
('countries','Iran'),
('countries','Iraq'),
('countries','Ireland'),
('countries','Israel'),
('countries','Italy'),
('countries','Jamaica'),
('countries','Japan'),
('countries','Jordan'),
('countries','Kazakhstan'),
('countries','Kenya'),
('countries','Kosovo'),
('countries','Kuwait'),
('countries','Kyrgyzstan'),
('countries','Laos'),
('countries','Latvia'),
('countries','Lebanon'),
('countries','Lesotho'),
('countries','Liberia'),
('countries','Libya'),
('countries','Lithuania'),
('countries','Luxembourg'),
('countries','Macedonia'),
('countries','Madagascar'),
('countries','Malawi'),
('countries','Malaysia'),
('countries','Mali'),
('countries','Mauritania'),
('countries','Mexico'),
('countries','Moldova'),
('countries','Mongolia'),
('countries','Montenegro'),
('countries','Morocco'),
('countries','Mozambique'),
('countries','Myanmar'),
('countries','N. Cyprus'),
('countries','Namibia'),
('countries','Nepal'),
('countries','Netherlands'),
('countries','New Caledonia'),
('countries','New Zealand'),
('countries','Nicaragua'),
('countries','Niger'),
('countries','Nigeria'),
('countries','North Korea'),
('countries','Norway'),
('countries','Oman'),
('countries','Pakistan'),
('countries','Palestine'),
('countries','Panama'),
('countries','Papua New Guinea'),
('countries','Paraguay'),
('countries','Peru'),
('countries','Philippines'),
('countries','Poland'),
('countries','Portugal'),
('countries','Puerto Rico'),
('countries','Qatar'),
('countries','Romania'),
('countries','Russia'),
('countries','Rwanda'),
('countries','S. Sudan'),
('countries','Saudi Arabia'),
('countries','Senegal'),
('countries','Serbia'),
('countries','Sierra Leone'),
('countries','Slovakia'),
('countries','Slovenia'),
('countries','Solomon Is.'),
('countries','Somalia'),
('countries','Somaliland'),
('countries','South Africa'),
('countries','South Korea'),
('countries','Spain'),
('countries','Sri Lanka'),
('countries','Sudan'),
('countries','Suriname'),
('countries','Sweden'),
('countries','Switzerland'),
('countries','Syria'),
('countries','Taiwan'),
('countries','Tajikistan'),
('countries','Tanzania'),
('countries','Thailand'),
('countries','Timor-Leste'),
('countries','Togo'),
('countries','Trinidad and Tobago'),
('countries','Tunisia'),
('countries','Turkey'),
('countries','Turkmenistan'),
('countries','Uganda'),
('countries','Ukraine'),
('countries','United Arab Emirates'),
('countries','United Kingdom'),
('countries','United States of America'),
('countries','Uruguay'),
('countries','Uzbekistan'),
('countries','Vanuatu'),
('countries','Venezuela'),
('countries','Vietnam'),
('countries','W. Sahara'),
('countries','Yemen'),
('countries','Zambia'),
('countries','Zimbabwe'),
('countries','eSwatini'),
('states','Alabama'),
('states','Alaska'),
('states','Arizona'),
('states','Arkansas'),
('states','California'),
('states','Colorado'),
('states','Connecticut'),
('states','Delaware'),
('states','Florida'),
('states','Georgia'),
('states','Hawaii'),
('states','Idaho'),
('states','Illinois'),
('states','Indiana'),
('states','Iowa'),
('states','Kansas'),
('states','Kentucky'),
('states','Louisiana'),
('states','Maine'),
('states','Maryland'),
('states','Massachusetts'),
('states','Michigan'),
('states','Minnesota'),
('states','Mississippi'),
('states','Missouri'),
('states','Montana'),
('states','Nebraska'),
('states','Nevada'),
('states','New Hampshire'),
('states','New Jersey'),
('states','New Mexico'),
('states','New York'),
('states','North Carolina'),
('states','North Dakota'),
('states','Ohio'),
('states','Oklahoma'),
('states','Oregon'),
('states','Pennsylvania'),
('states','Rhode Island'),
('states','South Carolina'),
('states','South Dakota'),
('states','Tennessee'),
('states','Texas'),
('states','Utah'),
('states','Vermont'),
('states','Virginia'),
('states','Washington'),
('states','West Virginia'),
('states','Wisconsin'),
('states','Wyoming')
on conflict do nothing;
create or replace function public.z_travel_vote(p_device text,p_user bigint default null,p_request uuid default null,p_kind text default null,p_place text default null) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare guest_id uuid; account_id uuid; voter_id uuid; used integer; problem text; existing public.z_travel_votes; result jsonb;
begin
 if p_device is null or p_device !~ '^[a-f0-9]{64}$' or (p_user is not null and p_user<=0) then raise exception 'Invalid voter'; end if;
 -- Serialize identity merging and allowance checks, including simultaneous browser tabs.
 perform pg_advisory_xact_lock(726031927);
 select voter into guest_id from z_travel_identities where identity='device:'||p_device;
 if p_user is not null then select voter into account_id from z_travel_identities where identity='kick:'||p_user::text; end if;
 voter_id:=coalesce(account_id,guest_id);
 if voter_id is null then insert into z_travel_voters default values returning id into voter_id; end if;
 if account_id is not null and guest_id is not null and account_id<>guest_id then
  update z_travel_votes set voter=account_id where voter=guest_id;
  update z_travel_identities set voter=account_id where voter=guest_id;
  delete from z_travel_voters where id=guest_id;
 end if;
 insert into z_travel_identities(identity,voter) values('device:'||p_device,voter_id) on conflict(identity) do nothing;
 if p_user is not null then insert into z_travel_identities(identity,voter) values('kick:'||p_user::text,voter_id) on conflict(identity) do nothing; end if;
 select count(*) into used from z_travel_votes where voter=voter_id;
 if p_request is not null then
  select * into existing from z_travel_votes where id=p_request;
  if found then
   if existing.voter<>voter_id or existing.kind<>p_kind or existing.place<>p_place then problem:='That request has already been used.'; end if;
  elsif not exists(select 1 from z_travel_destinations where kind=p_kind and place=p_place) then problem:='Choose a valid destination.';
  elsif used>=3 then problem:='You have used all 3 votes.';
  else insert into z_travel_votes(id,voter,kind,place) values(p_request,voter_id,p_kind,p_place);used:=used+1;
  end if;
 end if;
 select jsonb_build_object('used',used,'remaining',greatest(0,3-used),'destinations',coalesce(jsonb_agg(jsonb_build_object('kind',d.kind,'place',d.place,'votes',coalesce(v.total,0)) order by coalesce(v.total,0) desc,d.place),'[]'::jsonb)) into result
 from z_travel_destinations d left join (select kind,place,count(*) total from z_travel_votes group by kind,place) v using(kind,place);
 if problem is not null then result:=result||jsonb_build_object('error',problem);end if;
 return result;
end $$;
revoke all on function public.z_travel_vote(text,bigint,uuid,text,text) from public,anon,authenticated;
grant execute on function public.z_travel_vote(text,bigint,uuid,text,text) to service_role;
commit;
