-- 90% approachable mental math, 10% very easy general questions.
-- Preserve old questions and historical rounds; only change future selection.
begin;
update public.z_questions set enabled=false where enabled;
insert into public.z_questions(question,answers,category,enabled,last_used_at) values
('What is 17 + 8?',array['25','twenty five'],'Mental Math',true,null),
('What is 24 + 19?',array['43','forty three'],'Mental Math',true,null),
('What is 36 + 15?',array['51','fifty one'],'Mental Math',true,null),
('What is 48 + 12?',array['60','sixty'],'Mental Math',true,null),
('What is 27 + 16?',array['43','forty three'],'Mental Math',true,null),
('What is 65 + 18?',array['83','eighty three'],'Mental Math',true,null),
('What is 39 + 24?',array['63','sixty three'],'Mental Math',true,null),
('What is 54 + 17?',array['71','seventy one'],'Mental Math',true,null),
('What is 28 + 35?',array['63','sixty three'],'Mental Math',true,null),
('What is 46 + 29?',array['75','seventy five'],'Mental Math',true,null),
('What is 72 + 19?',array['91','ninety one'],'Mental Math',true,null),
('What is 58 + 26?',array['84','eighty four'],'Mental Math',true,null),
('What is 34 + 28?',array['62','sixty two'],'Mental Math',true,null),
('What is 63 + 17?',array['80','eighty'],'Mental Math',true,null),
('What is 49 + 14?',array['63','sixty three'],'Mental Math',true,null),
('What is 23 + 38?',array['61','sixty one'],'Mental Math',true,null),
('What is 57 + 16?',array['73','seventy three'],'Mental Math',true,null),
('What is 68 + 12?',array['80','eighty'],'Mental Math',true,null),
('What is 29 + 27?',array['56','fifty six'],'Mental Math',true,null),
('What is 45 + 36?',array['81','eighty one'],'Mental Math',true,null),
('What is 42 - 17?',array['25','twenty five'],'Mental Math',true,null),
('What is 63 - 28?',array['35','thirty five'],'Mental Math',true,null),
('What is 80 - 35?',array['45','forty five'],'Mental Math',true,null),
('What is 91 - 46?',array['45','forty five'],'Mental Math',true,null),
('What is 54 - 19?',array['35','thirty five'],'Mental Math',true,null),
('What is 72 - 24?',array['48','forty eight'],'Mental Math',true,null),
('What is 100 - 37?',array['63','sixty three'],'Mental Math',true,null),
('What is 68 - 29?',array['39','thirty nine'],'Mental Math',true,null),
('What is 85 - 48?',array['37','thirty seven'],'Mental Math',true,null),
('What is 76 - 18?',array['58','fifty eight'],'Mental Math',true,null),
('What is 53 - 26?',array['27','twenty seven'],'Mental Math',true,null),
('What is 90 - 56?',array['34','thirty four'],'Mental Math',true,null),
('What is 64 - 17?',array['47','forty seven'],'Mental Math',true,null),
('What is 81 - 33?',array['48','forty eight'],'Mental Math',true,null),
('What is 95 - 27?',array['68','sixty eight'],'Mental Math',true,null),
('What is 70 - 38?',array['32','thirty two'],'Mental Math',true,null),
('What is 57 - 29?',array['28','twenty eight'],'Mental Math',true,null),
('What is 88 - 49?',array['39','thirty nine'],'Mental Math',true,null),
('What is 61 - 24?',array['37','thirty seven'],'Mental Math',true,null),
('What is 99 - 45?',array['54','fifty four'],'Mental Math',true,null),
('What is 6 times 7?',array['42','forty two'],'Mental Math',true,null),
('What is 8 times 9?',array['72','seventy two'],'Mental Math',true,null),
('What is 7 times 8?',array['56','fifty six'],'Mental Math',true,null),
('What is 12 times 4?',array['48','forty eight'],'Mental Math',true,null),
('What is 9 times 6?',array['54','fifty four'],'Mental Math',true,null),
('What is 11 times 7?',array['77','seventy seven'],'Mental Math',true,null),
('What is 8 times 4?',array['32','thirty two'],'Mental Math',true,null),
('What is 12 times 6?',array['72','seventy two'],'Mental Math',true,null),
('What is 7 times 9?',array['63','sixty three'],'Mental Math',true,null),
('What is 5 times 13?',array['65','sixty five'],'Mental Math',true,null),
('What is 6 times 8?',array['48','forty eight'],'Mental Math',true,null),
('What is 11 times 8?',array['88','eighty eight'],'Mental Math',true,null),
('What is 4 times 14?',array['56','fifty six'],'Mental Math',true,null),
('What is 3 times 17?',array['51','fifty one'],'Mental Math',true,null),
('What is 12 times 7?',array['84','eighty four'],'Mental Math',true,null),
('What is 9 times 9?',array['81','eighty one'],'Mental Math',true,null),
('What is 8 times 8?',array['64','sixty four'],'Mental Math',true,null),
('What is 6 times 12?',array['72','seventy two'],'Mental Math',true,null),
('What is 7 times 7?',array['49','forty nine'],'Mental Math',true,null),
('What is 4 times 16?',array['64','sixty four'],'Mental Math',true,null),
('What is 56 divided by 7?',array['8','eight'],'Mental Math',true,null),
('What is 72 divided by 8?',array['9','nine'],'Mental Math',true,null),
('What is 81 divided by 9?',array['9','nine'],'Mental Math',true,null),
('What is 96 divided by 12?',array['8','eight'],'Mental Math',true,null),
('What is 84 divided by 7?',array['12','twelve'],'Mental Math',true,null),
('What is 63 divided by 9?',array['7','seven'],'Mental Math',true,null),
('What is 48 divided by 6?',array['8','eight'],'Mental Math',true,null),
('What is 90 divided by 10?',array['9','nine'],'Mental Math',true,null),
('What is 100 divided by 4?',array['25','twenty five'],'Mental Math',true,null),
('What is 60 divided by 5?',array['12','twelve'],'Mental Math',true,null),
('What is 88 divided by 8?',array['11','eleven'],'Mental Math',true,null),
('What is 99 divided by 9?',array['11','eleven'],'Mental Math',true,null),
('What is 54 divided by 6?',array['9','nine'],'Mental Math',true,null),
('What is 36 divided by 4?',array['9','nine'],'Mental Math',true,null),
('What is 64 divided by 8?',array['8','eight'],'Mental Math',true,null),
('What is 75 divided by 5?',array['15','fifteen'],'Mental Math',true,null),
('What is 42 divided by 7?',array['6','six'],'Mental Math',true,null),
('What is 80 divided by 5?',array['16','sixteen'],'Mental Math',true,null),
('What is 120 divided by 10?',array['12','twelve'],'Mental Math',true,null),
('What is 108 divided by 9?',array['12','twelve'],'Mental Math',true,null),
('What is 10% of 80?',array['8','eight'],'Mental Math',true,null),
('What is 10% of 150?',array['15','fifteen'],'Mental Math',true,null),
('What is 50% of 46?',array['23','twenty three'],'Mental Math',true,null),
('What is 50% of 90?',array['45','forty five'],'Mental Math',true,null),
('What is 25% of 80?',array['20','twenty'],'Mental Math',true,null),
('What is 25% of 100?',array['25','twenty five'],'Mental Math',true,null),
('What is 20% of 50?',array['10','ten'],'Mental Math',true,null),
('What is 20% of 100?',array['20','twenty'],'Mental Math',true,null),
('What is 10% of 250?',array['25','twenty five'],'Mental Math',true,null),
('What is 50% of 74?',array['37','thirty seven'],'Mental Math',true,null),
('How many days are in a week?',array['7','seven'],'Easy General',true,null),
('How many sides does a triangle have?',array['3','three'],'Easy General',true,null),
('How many wheels does a standard bicycle have?',array['2','two'],'Easy General',true,null),
('How many months are in a year?',array['12','twelve'],'Easy General',true,null),
('How many minutes are in one hour?',array['60','sixty'],'Easy General',true,null),
('How many legs does a spider have?',array['8','eight'],'Easy General',true,null),
('What planet do we live on?',array['earth'],'Easy General',true,null),
('What animal says meow?',array['cat'],'Easy General',true,null),
('What is frozen water called?',array['ice'],'Easy General',true,null),
('What color is a ripe banana?',array['yellow'],'Easy General',true,null)
on conflict(question) do update set answers=excluded.answers,category=excluded.category,enabled=true,last_used_at=null;
commit;
select category,count(*) as active_questions from public.z_questions where enabled group by category order by category;
