import React,{useEffect,useRef,useState} from 'react';
import {translate as tr} from '../localization/language.mjs';
export default function TravelVotes(){
 const [open,setOpen]=useState(false),[tab,setTab]=useState('countries'),[search,setSearch]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const container=useRef(null);
 useEffect(()=>{if(!open)return;const close=e=>{if(e.type==='keydown'){if(e.key==='Escape')setOpen(false);}else if(!container.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',close);};},[open]);
 const active=useRef(false),version=useRef(0),pending=useRef(null);
 async function refresh(){const v=version.current;try{const r=await fetch('/api/site?votes=1');const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load votes.');if(v===version.current&&!active.current){setData(j);if(!pending.current)setError('');}}catch(e){if(v===version.current&&!active.current)setError(e.message);}}
 useEffect(()=>{if(!open)return;refresh();const t=setInterval(()=>{if(!document.hidden&&!active.current)refresh();},10000);return()=>{clearInterval(t);version.current++;};},[open]);
 async function vote(item){if(active.current||!data||(!pending.current&&data.remaining<=0))return;active.current=true;version.current++;setBusy(true);setError('');const b=pending.current||{kind:item.kind,place:item.place,requestId:crypto.randomUUID()};pending.current=b;try{const r=await fetch('/api/site?votes=1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const j=await r.json();if(j.destinations)setData(j);if(!r.ok){if(r.status<500)pending.current=null;throw Error(j.error||'Unable to save your vote.');}pending.current=null;}catch(e){setError(e.message);}finally{active.current=false;setBusy(false);}}
 const items=(data?.destinations||[]).filter(x=>x.kind===tab&&x.place.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>b.votes-a.votes||a.place.localeCompare(b.place)).slice(0,search.trim()?8:5);
 return <section ref={container} className="map-votes"><button className="travel-vote-toggle" aria-expanded={open} aria-controls="travel-vote-panel" onClick={()=>setOpen(x=>!x)}>{tr('Where Should Zeek Go Next?')} <span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<div id="travel-vote-panel" className="travel-vote-panel"><header><div><h2>{tr('Choose the next adventure')}</h2><p>{tr('3 votes across countries and states.')}</p></div><strong aria-live="polite">{data?`${data.remaining} / 3 ${tr('votes left')}`:tr('Loading…')}</strong></header><div className="travel-vote-tools"><div role="tablist" aria-label="Destinations">{[['countries','Countries'],['states','States']].map(([key,label])=><button role="tab" id={'vote-tab-'+key} aria-controls="vote-results" aria-selected={tab===key} key={key} onClick={()=>{setTab(key);setSearch('');}}>{tr(label)}</button>)}</div><label>{tr('Search destinations')}<input value={search} onChange={e=>setSearch(e.target.value)} type="search" maxLength={100}/></label></div>{error&&<div role="alert" className="travel-vote-error">{error} <button disabled={busy} onClick={()=>pending.current?vote(pending.current):refresh()}>{tr('Retry')}</button></div>}<div className="travel-results-label">{tr(search.trim()?'Search results':'Top 5 destinations')}</div><div id="vote-results" role="tabpanel" aria-labelledby={'vote-tab-'+tab} className="travel-vote-results" aria-busy={busy}>{items.map(item=><article key={item.kind+item.place}><strong>{item.place}</strong><span>{item.votes} {tr(item.votes===1?'vote':'votes')}</span><button disabled={busy||!data.remaining||!!pending.current} aria-label={`${tr('Vote for')} ${item.place}`} onClick={()=>vote(item)}>{tr(busy&&pending.current?.place===item.place?'Saving…':'Vote')}</button></article>)}{data&&!items.length&&<p>{tr('No results found.')}</p>}</div><p className="travel-vote-note">{tr('Sign in with Kick to keep your votes across devices. Guest votes are saved on this device.')}</p></div>}</section>;
}
