import countries from '../data/countries.json' with {type:'json'};
import states from '../data/states.json' with {type:'json'};
import {invalid} from './security.mjs';
export function youtubeId(input){if(typeof input!=='string'||input.length>2048)throw invalid('Paste a valid YouTube URL.');let u;try{u=new URL(input);}catch{throw invalid('Paste a valid YouTube URL.');}if(u.protocol!=='https:'||u.username||u.password)throw invalid('Paste a valid YouTube URL.');const h=u.hostname.replace(/^www\./,'');const id=h==='youtu.be'?u.pathname.slice(1):['youtube.com','m.youtube.com'].includes(h)?(u.pathname==='/watch'?u.searchParams.get('v'):u.pathname.match(/^\/(?:shorts|live|embed)\/([^/]+)\/?$/)?.[1]):null;if(!/^[\w-]{11}$/.test(id||''))throw invalid('Paste a valid YouTube video URL.');return id;}
const text=(v,n)=>{if(typeof v!=='string'||v.length>n)throw invalid('Please shorten the text and try again.');return v.trim();};
export function safeLink(v){v=text(v||'',2048);if(!v)return '';let u;try{u=new URL(v);}catch{throw invalid('Links must be complete https:// addresses.');}if(u.protocol!=='https:'||u.username||u.password||u.port||/^(localhost|127\.|0\.|\[|10\.|192\.168\.|169\.254\.)/i.test(u.hostname))throw invalid('Links must be public https:// addresses.');return u.href;}
export function locationVideos(v){const list=v.videos===undefined?(v.video?[{title:'Watch stream / video',url:v.video}]:[]):v.videos;if(!Array.isArray(list)||list.length>20)throw invalid('Use up to 20 videos per location.');return list.map(x=>{if(!x||typeof x!=='object'||Array.isArray(x))throw invalid('Invalid video link.');const url=safeLink(x.url);if(!url)throw invalid('Enter a video URL.');return {title:text(x.title||'Watch video',100),url};});}
export function locationInput(v){if(!v||typeof v!=='object'||Array.isArray(v)||!['world','usa'].includes(v.scope)||!['visited','upcoming'].includes(v.status))throw invalid('Choose a location and status.');if(typeof v.placeId!=='string'||!(v.scope==='world'?countries.includes(v.placeId):Object.hasOwn(states,v.placeId)))throw invalid('Choose a destination from the list.');if(typeof v.id!=='string'||!/^[a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12}$/i.test(v.id))throw invalid('Invalid location.');return {id:v.id,scope:v.scope,placeId:v.placeId,name:v.scope==='world'?v.placeId:states[v.placeId],location:text(v.location||'',100),status:v.status,note:text(v.note||'',300),link:safeLink(v.link),video:'',videos:locationVideos(v)};}
export function editContent(current,b){if(!Number.isSafeInteger(b.revision)||b.revision<0)throw invalid('Refresh this page before saving.');const next=structuredClone(current);if(b.action==='video')next.latestVideo={id:youtubeId(b.url),title:text(b.title||'Latest from ZeekFusion',160)};else if(b.action==='mcMusic')next.mcMusicUrl=safeLink(b.url);else if(b.action==='how'){const h=b.howItWorks;if(!h||!Array.isArray(h.sections)||h.sections.length!==3)throw invalid('Use three How It Works sections.');const clean=(v,n,required=false)=>{const t=text(v,n);if(required&&!t)throw invalid('Enter a heading.');return t;};next.howItWorks={title:clean(h.title,160,true),intro:clean(h.intro,1000),sections:h.sections.map(s=>{if(!s||typeof s!=='object')throw invalid('Invalid section.');return {title:clean(s.title,200,true),body:clean(s.body,4000)};})};}else if(b.action==='location'){const item=locationInput(b.location),index=next.locations.findIndex(x=>x.id===item.id);if(index<0){if(next.locations.length>=500)throw invalid('Location limit reached.');next.locations.push(item);}else next.locations[index]=item;}else if(b.action==='delete'){if(typeof b.id!=='string'||!next.locations.some(x=>x.id===b.id))throw invalid('Location not found.');next.locations=next.locations.filter(x=>x.id!==b.id);}else throw invalid('Unknown update.');return next;}
