export async function db(path,{method='GET',body,prefer}={}) {
  const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;
  if(!base||!key) throw new Error('Database connection is not configured.');
  const r=await fetch(`${base}/rest/v1/${path}`,{method,headers:{apikey:key,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});
  const t=await r.text();
  if(!r.ok){console.error('Database request failed',path.split('?')[0],r.status,t.slice(0,300));const known=['Reward is cooling down. Please try again shortly.','User not found','Invalid adjustment','Owner and reason required','Choose rock, paper or scissors','Finish your active game first','Game already finished','Game changed; refresh and try again','Choose the other direction','Choose an unrevealed tile','Invalid move','Insufficient free-earned Zs','Please wait a moment between games','Maximum five open challenges','Challenge unavailable','Challenge already closed','You cannot accept your own challenge','Choose heads or tails','Invalid wager','Insufficient Zs','Reward unavailable','Conversions unavailable or invalid amount','Entries are closed','Giveaway must be closed for entries'];let detail;try{detail=JSON.parse(t).message;}catch{}if(path.split('?')[0]==='z_rewards'&&r.status===409){let error;try{error=JSON.parse(t);}catch{}if(error?.code==='23505'&&String(error.message).includes('z_rewards_command_name_unique'))throw Object.assign(new Error('That command name is already used by another reward.'),{status:409});}if(known.includes(detail))throw Object.assign(new Error(detail==='Insufficient free-earned Zs'?'Not enough Zs available for this wager.':detail),{status:400});throw new Error('The database could not complete this action.');}
  return t?JSON.parse(t):null;
}
export const rpc=(name,body={})=>db(`rpc/${name}`,{method:'POST',body});
export async function configuration(){return (await db('z_config?id=eq.1&select=settings'))[0].settings;}
