import crypto from 'node:crypto';
import {db,rpc} from './db.mjs';
import {seal,unseal} from './auth.mjs';
import {BROADCASTER} from './domain.mjs';
let appToken;
export async function tokenRequest(fields){const r=await fetch('https://id.kick.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...fields,client_id:process.env.KICK_CLIENT_ID,client_secret:process.env.KICK_CLIENT_SECRET}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('Kick authorization failed. Reconnect Kick from your Vault controls.');return r.json();}
export async function appAccess(){if(!appToken||appToken.until<Date.now()){const t=await tokenRequest({grant_type:'client_credentials'});appToken={value:t.access_token,until:Date.now()+(Number(t.expires_in)-120)*1000};}return appToken.value;}
export async function kickGet(path,token){const r=await fetch(`https://api.kick.com/public/v1/${path}`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Kick request failed (${r.status}).`);return r.json();}
export async function saveBot(t){await db('z_bot?on_conflict=id',{method:'POST',prefer:'resolution=merge-duplicates',body:{id:1,encrypted_tokens:seal({...t,expires_at:Date.now()+Number(t.expires_in)*1000}),updated_at:new Date().toISOString()}});}
export async function botAccess(){const row=(await db('z_bot?id=eq.1&select=encrypted_tokens'))[0];if(!row)throw new Error('Connect your Kick account in Vault controls to activate the question bot.');let t=unseal(row.encrypted_tokens);if(t.expires_at<Date.now()+120000){const owner=crypto.randomUUID();if(!await rpc('z_lock',{p_name:'bot-refresh',p_owner:owner,p_seconds:30}))throw new Error('Kick connection is refreshing.');try{const fresh=unseal((await db('z_bot?id=eq.1&select=encrypted_tokens'))[0].encrypted_tokens);if(fresh.expires_at>Date.now()+120000)return fresh.access_token;t=await tokenRequest({grant_type:'refresh_token',refresh_token:fresh.refresh_token});await saveBot(t);}finally{await rpc('z_unlock',{p_name:'bot-refresh',p_owner:owner});}}return t.access_token;}
export async function sendChat(content){const token=await botAccess();const r=await fetch('https://api.kick.com/public/v1/chat',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({broadcaster_user_id:BROADCASTER,type:'user',content:content.slice(0,490)}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Kick chat could not send (${r.status}). Reconnect Kick if this persists.`);const b=await r.json();if(b.data?.is_sent!==true)throw new Error('Kick did not confirm the chat message.');}
export async function flushOutbox(){const owner=crypto.randomUUID();if(!await rpc('z_lock',{p_name:'outbox',p_owner:owner,p_seconds:55}))return;
 try{const rows=await db('z_outbox?status=eq.pending&order=created_at.asc&limit=3');for(const row of rows){if(row.round_id){const r=(await db(`z_rounds?id=eq.${row.round_id}&select=status`))[0];if(r?.status!=='pending'){await db(`z_outbox?id=eq.${row.id}`,{method:'PATCH',body:{status:'cancelled'}});continue;}}
 // Claim once before delivery. Ambiguous network failures are surfaced, not replayed into chat.
 await db(`z_outbox?id=eq.${row.id}`,{method:'PATCH',body:{status:'sending',attempts:row.attempts+1}});
 try{await sendChat(row.content);await db(`z_outbox?id=eq.${row.id}`,{method:'PATCH',body:{status:'sent',sent_at:new Date().toISOString()}});if(row.round_id)await rpc('z_open_round',{p_round:row.round_id});await db('z_runtime?id=eq.1',{method:'PATCH',body:{bot_error:null}});}catch(e){await db(`z_outbox?id=eq.${row.id}`,{method:'PATCH',body:{status:'failed'}});if(row.round_id)await db(`z_rounds?id=eq.${row.round_id}`,{method:'PATCH',body:{status:'cancelled'}});await db('z_runtime?id=eq.1',{method:'PATCH',body:{bot_error:e.message}});break;}}
 }finally{await rpc('z_unlock',{p_name:'outbox',p_owner:owner});}}
export async function tick(){const owner=crypto.randomUUID();if(!await rpc('z_lock',{p_name:'tick',p_owner:owner,p_seconds:55}))return {busy:true};try{const c=(await kickGet('channels?slug=zeekfusion',await appAccess())).data?.[0];if(!c||Number(c.broadcaster_user_id)!==BROADCASTER)throw new Error('Channel status unavailable.');await db('z_runtime?id=eq.1',{method:'PATCH',body:{is_live:c.stream?.is_live===true,checked_at:new Date().toISOString()}});if(c.stream?.is_live!==true){await db('z_rounds?status=in.(pending,open)',{method:'PATCH',body:{status:'cancelled'}});return {live:false};}await botAccess();await rpc('z_start_round');await flushOutbox();return {live:true};}catch(e){await db('z_runtime?id=eq.1',{method:'PATCH',body:{bot_error:e.message}});throw e;}finally{await rpc('z_unlock',{p_name:'tick',p_owner:owner});}}
