import {site} from './auth.mjs';
export const providers=['youtube','tiktok','instagram'];
export const redirect=p=>site()+'/api/clips/callback/'+p;
const bad=message=>Object.assign(new Error(message),{status:400});
export async function json(url,options={}){const response=await fetch(url,{...options,signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok||data.error&&(typeof data.error==='string'||data.error.code&&data.error.code!=='ok'))throw bad('The platform rejected this request. Check the app permissions or reconnect the account.');return data;}
const form=(url,body)=>json(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)});
export function authorize(platform,app,state){let url,params={client_id:app.id,redirect_uri:redirect(platform),response_type:'code',state};if(platform==='youtube'){url='https://accounts.google.com/o/oauth2/v2/auth';Object.assign(params,{scope:'https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/yt-analytics.readonly',access_type:'offline',prompt:'consent'});}else if(platform==='tiktok'){url='https://www.tiktok.com/v2/auth/authorize/';delete params.client_id;Object.assign(params,{client_key:app.id,scope:'user.info.basic,video.list'});}else{url='https://www.instagram.com/oauth/authorize';Object.assign(params,{scope:'instagram_business_basic,instagram_business_manage_insights',enable_fb_login:'0',force_authentication:'1'});}return url+'?'+new URLSearchParams(params);}
export async function exchange(p,app,code){let t;if(p==='youtube')t=await form('https://oauth2.googleapis.com/token',{client_id:app.id,client_secret:app.secret,code,grant_type:'authorization_code',redirect_uri:redirect(p)});else if(p==='tiktok')t=await form('https://open.tiktokapis.com/v2/oauth/token/',{client_key:app.id,client_secret:app.secret,code,grant_type:'authorization_code',redirect_uri:redirect(p)});else{const short=await form('https://api.instagram.com/oauth/access_token',{client_id:app.id,client_secret:app.secret,code,grant_type:'authorization_code',redirect_uri:redirect(p)});t=await json('https://graph.instagram.com/access_token?'+new URLSearchParams({grant_type:'ig_exchange_token',client_secret:app.secret,access_token:short.access_token}));}if(!t.access_token)throw bad('No access token returned. Please reconnect.');return {...t,expires:Date.now()+Number(t.expires_in||3600)*1000,issued:Date.now()};}
export async function refresh(p,app,token){if(token.expires>Date.now()+(p==='instagram'?7*86400000:300000)||p==='instagram'&&Date.now()-token.issued<86400000)return token;let next;if(p==='youtube')next=await form('https://oauth2.googleapis.com/token',{client_id:app.id,client_secret:app.secret,refresh_token:token.refresh_token,grant_type:'refresh_token'});else if(p==='tiktok')next=await form('https://open.tiktokapis.com/v2/oauth/token/',{client_key:app.id,client_secret:app.secret,refresh_token:token.refresh_token,grant_type:'refresh_token'});else next=await json('https://graph.instagram.com/refresh_access_token?'+new URLSearchParams({grant_type:'ig_refresh_token',access_token:token.access_token}));if(!next.access_token)throw bad('The account needs reconnecting.');return {...token,...next,expires:Date.now()+Number(next.expires_in||3600)*1000,issued:Date.now()};}
export const get=(url,token)=>json(url,{headers:{Authorization:'Bearer '+token.access_token}});
export async function account(p,token){if(p==='youtube'){const data=await get('https://www.googleapis.com/youtube/v3/channels?part=id,snippet,contentDetails&mine=true',token);const c=data.items?.[0];if(!c)throw bad('No YouTube channel found.');return {id:c.id,name:c.snippet.title,uploads:c.contentDetails.relatedPlaylists.uploads};}if(p==='instagram'){const c=await get('https://graph.instagram.com/v23.0/me?fields=user_id,username',token);return {id:c.user_id||c.id,name:c.username};}const c=(await get('https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name',token)).data.user;return {id:c.open_id,name:c.display_name};}
const count=value=>value==null?null:Number.isSafeInteger(Number(value))&&Number(value)>=0?Number(value):null;
export async function videoPage(p,token,a,cursor){
 if(p==='tiktok'){const data=await json('https://open.tiktokapis.com/v2/video/list/?fields=id,title,cover_image_url,share_url,view_count,create_time',{method:'POST',headers:{Authorization:'Bearer '+token.access_token,'Content-Type':'application/json'},body:JSON.stringify({max_count:20,...(cursor?.after?{cursor:cursor.after}:{})})});const d=data.data;return {clips:d.videos.map(v=>({id:v.id,title:v.title||'ZeekFusion moment',url:v.share_url,thumbnail:v.cover_image_url,views:count(v.view_count),published_at:new Date(v.create_time*1000).toISOString()})),cursor:d.has_more?{after:d.cursor}:null};}
 if(p==='instagram'){const d=await get('https://graph.instagram.com/v23.0/'+a.id+'/media?'+new URLSearchParams({fields:'id,caption,media_product_type,permalink,thumbnail_url,timestamp',limit:'20',...(cursor?.after?{after:cursor.after}:{})}),token);const clips=[];const reels=d.data.filter(v=>v.media_product_type==='REELS');for(let i=0;i<reels.length;i+=5){clips.push(...await Promise.all(reels.slice(i,i+5).map(async v=>{const stats=await get('https://graph.instagram.com/v23.0/'+v.id+'/insights?metric=views',token);const value=stats.data?.find(x=>x.name==='views');return {id:new URL(v.permalink).pathname.split('/').filter(Boolean)[1],title:v.caption||'ZeekFusion Reel',url:v.permalink,thumbnail:v.thumbnail_url,views:count(value?.values?.[0]?.value??value?.total_value?.value),published_at:v.timestamp};})));}return {clips,cursor:d.paging?.next?{after:d.paging.cursors.after}:null};}
 const d=await get('https://www.googleapis.com/youtube/v3/playlistItems?'+new URLSearchParams({part:'contentDetails',playlistId:a.uploads,maxResults:'50',...(cursor?.after?{pageToken:cursor.after}:{})}),token);const ids=d.items.map(v=>v.contentDetails.videoId);if(!ids.length)return {clips:[],cursor:null};
 // Query each upload page, rather than the Analytics "top 200" report.
 const stats=await get('https://youtubeanalytics.googleapis.com/v2/reports?'+new URLSearchParams({ids:'channel==MINE',startDate:'2005-01-01',endDate:new Date().toISOString().slice(0,10),metrics:'views',dimensions:'video,creatorContentType',filters:'video=='+ids.join(','),maxResults:'200'}),token);
 const shortIds=new Set((stats.rows||[]).filter(row=>row[1]==='SHORTS').map(row=>row[0]));const videos=await get('https://www.googleapis.com/youtube/v3/videos?'+new URLSearchParams({part:'snippet,statistics,status',id:ids.join(',')}),token);
 return {clips:videos.items.filter(v=>shortIds.has(v.id)&&v.status.privacyStatus==='public').map(v=>({id:v.id,title:v.snippet.title,url:'https://www.youtube.com/shorts/'+v.id,thumbnail:(v.snippet.thumbnails.maxres||v.snippet.thumbnails.high||v.snippet.thumbnails.default).url,views:count(v.statistics.viewCount),published_at:v.snippet.publishedAt})),cursor:d.nextPageToken?{after:d.nextPageToken}:null};
}
