import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import countries from '../data/countries.json';
import states from '../data/states.json';
import './Admin.css';
const empty=()=>({id:crypto.randomUUID(),scope:'world',placeId:'',location:'',status:'visited',note:'',link:'',video:''});
export default function Admin(){const [data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[denied,setDenied]=useState(0),[busy,setBusy]=useState(false),[url,setUrl]=useState(''),[title,setTitle]=useState(''),[item,setItem]=useState(empty),[search,setSearch]=useState('');
async function load(){setError('');setDenied(0);try{const r=await fetch('/api/site?admin=1'),j=await r.json();if(!r.ok){if([401,403].includes(r.status))setDenied(r.status);throw Error(j.error||'Unable to load content.');}setData(j);setUrl('https://www.youtube.com/watch?v='+j.content.latestVideo.id);setTitle(j.content.latestVideo.title);}catch(e){setError(e.message);}}
useEffect(()=>{load();},[]);
async function save(body){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/site',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,revision:data.revision})}),j=await r.json();if(!r.ok)throw Error(j.error||'Unable to save.');setData(j);setMessage(body.action==='video'?'Video updated. It is now on your homepage.':body.action==='delete'?'Location removed from the map.':'Location saved. Your map is updated.');if(body.action!=='video')setItem(empty());}catch(e){setError(e.message);}finally{setBusy(false);}}
if(!data)return <main className="content-admin"><p className="admin-eyebrow">ZEEKFUSION · CREATOR TOOLS</p><h1>Your site. Your updates.</h1>{!error?<p>Checking your Kick account…</p>:<><p role="alert">{denied===403?'This area is available only to the ZeekFusion owner account.':error}</p>{denied===401?<a className="admin-primary" href="/api/kick/login?returnTo=admin">Sign in with Kick →</a>:<button onClick={load}>Try again</button>}</>}<Link to="/">← Back to homepage</Link></main>;
const choices=item.scope==='world'?countries.map(n=>[n,n]):Object.entries(states).sort((a,b)=>a[1].localeCompare(b[1]));return <main className="content-admin"><header className="admin-header"><div><p className="admin-eyebrow">ZEEKFUSION · PRIVATE CREATOR TOOLS</p><h1>Make it yours.</h1><p>Update a video. Add a stop. Keep the community in the loop.</p></div><Link to="/">View homepage ↗</Link></header><nav className="admin-shortcuts">{[['admin-video','Latest video'],['admin-map','Travel map']].map(([id,label])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>{label}</button>)}<Link to="/market">Z Market controls ↗</Link></nav>{message&&<p className="admin-success" role="status">{message}</p>}{error&&<div className="admin-error" role="alert">{error} <button disabled={busy} onClick={load}>Reload saved content</button></div>}
<div className="admin-grid"><section id="admin-video" className="admin-card"><span className="admin-eyebrow">01 / HOMEPAGE</span><h2>Latest YouTube video</h2><p>Paste a YouTube video, Short, or live video URL.</p><form onSubmit={e=>{e.preventDefault();save({action:'video',url,title});}}><fieldset disabled={busy}><label>YouTube URL<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=…" maxLength={2048}/></label><label>Video title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160} placeholder="Latest from ZeekFusion"/></label><button className="admin-primary">{busy?'Saving…':'Update Video →'}</button></fieldset></form><a className="admin-video-preview" href={'https://www.youtube.com/watch?v='+data.content.latestVideo.id} target="_blank" rel="noreferrer"><img src={'https://i.ytimg.com/vi/'+data.content.latestVideo.id+'/hqdefault.jpg'} alt="Current homepage video"/><span>{data.content.latestVideo.title} ↗</span></a></section>
<section id="admin-map" className="admin-card"><span className="admin-eyebrow">02 / TRAVEL MAP</span><h2>{data.content.locations.some(x=>x.id===item.id)?'Edit location':'Add a location'}</h2><p>Choose a country or state. Add a city or stop name if you want.</p><form onSubmit={e=>{e.preventDefault();save({action:'location',location:item});}}><fieldset disabled={busy}><div className="admin-form-row"><label>Map<select value={item.scope} onChange={e=>setItem({...item,scope:e.target.value,placeId:''})}><option value="world">World</option><option value="usa">USA</option></select></label><label>Status<select value={item.status} onChange={e=>setItem({...item,status:e.target.value})}><option value="visited">Visited</option><option value="upcoming">Upcoming</option></select></label></div><label>{item.scope==='world'?'Country':'State'}<select required value={item.placeId} onChange={e=>setItem({...item,placeId:e.target.value})}><option value="">Choose a destination</option>{choices.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>City or stop name <small>optional</small><input value={item.location} maxLength={100} onChange={e=>setItem({...item,location:e.target.value})} placeholder="For example, Miami"/></label><label>Note <small>optional</small><input value={item.note} maxLength={300} onChange={e=>setItem({...item,note:e.target.value})} placeholder="What's happening here?"/></label><label>Destination link <small>optional</small><input type="url" value={item.link} maxLength={2048} onChange={e=>setItem({...item,link:e.target.value})} placeholder="https://…"/></label><label>Stream, VOD or video link <small>optional</small><input type="url" value={item.video} maxLength={2048} onChange={e=>setItem({...item,video:e.target.value})} placeholder="https://…"/></label><div className="admin-actions"><button className="admin-primary">{busy?'Saving…':'Save location →'}</button><button type="button" onClick={()=>setItem(empty())}>Clear / New</button></div></fieldset></form></section></div>
<section className="admin-card admin-locations"><div className="admin-header"><div><h2>Your destinations</h2><p>Changes appear on the public map automatically.</p></div><Link to="/map">View map ↗</Link></div><label>Find a location<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search country, state or stop…"/></label><div className="admin-location-list">{data.content.locations.filter(x=>(x.name+' '+x.location+' '+x.status).toLowerCase().includes(search.toLowerCase())).map(x=><article key={x.id}><div><strong>{x.location?x.location+' · ':''}{x.name}</strong><span>{x.scope==='world'?'World':'USA'} · {x.status}</span>{x.note&&<p>{x.note}</p>}</div><div className="admin-actions"><button disabled={busy} onClick={()=>{setItem(x);document.getElementById('admin-map')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}}>Edit</button><button disabled={busy} onClick={()=>save({action:'delete',id:x.id})}>Remove</button></div></article>)}</div></section></main>}
