import React,{useState,useEffect,useRef} from 'react';
import {amountZ as az,numberZ as n} from '../server/z-format.mjs';
import {Board} from './Arena';
import Blackjack,{blackjackDuration} from './Blackjack';
import {hitOdds} from '../server/blackjack-odds.mjs';
const names={coin:'Coin Flip',plinko:'Plinko',higher:'Higher or Lower',dice:'Dice Duel',mines:'Mines',rps:'Rock Paper Scissors',blackjack:'Blackjack',open:'Open Challenges'};
const symbols={coin:'◐',plinko:'⠿',higher:'♠',dice:'⚄',mines:'◇',rps:'✊',blackjack:'♠',open:'⚔'};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const cardName=v=>({1:'A',11:'J',12:'Q',13:'K'}[v]||v);
function Dice({values,rolling}){const [frame,setFrame]=useState(0);useEffect(()=>{if(!rolling)return;const t=setInterval(()=>setFrame(x=>x+1),90);return()=>clearInterval(t)},[rolling]);return <div className={`g-dice ${rolling?'rolling':''}`}>{[0,1].map(i=><div key={i} className="g-die"><span>{['⚀','⚁','⚂','⚃','⚄','⚅'][rolling?(frame+i*3)%6:(values?.[i]||1)-1]}</span><small>{i===0?'CREATOR':'CHALLENGER'}</small></div>)}</div>}
export default function Games({me,arena,onRefresh,onBusy}){
 const [mode,setMode]=useState('single'),[waiting,setWaiting]=useState(null);
 const [single,setSingle]=useState('plinko'),[duel,setDuel]=useState('coin');
 const [busy,setBusy]=useState(false),[animating,setAnimating]=useState(false),[pending,setPending]=useState(null),[message,setMessage]=useState(''),[visual,setVisual]=useState(null),[local,setLocal]=useState({}),[requestError,setRequestError]=useState(null);const mounted=useRef(true);const busyRef=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;onBusy(false)}},[]);
 useEffect(()=>{if(!busy)setLocal(previous=>{const next={...previous};for(const g of arena?.active||[]){const old=next[g.kind];if(old?.id===g.id&&(old.status!=='playing'||Number(old.result?.version)>Number(g.result?.version)))continue;next[g.kind]=g}return next})},[arena?.active]);
 const active=kind=>local[kind]||arena?.active?.find(g=>g.kind===kind);
 async function play(body){if(busyRef.current)return;busyRef.current=true;setBusy(true);setWaiting(body);onBusy(true);setMessage('');setRequestError(null);try{const r=await fetch('/api/arcade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Please try again.');const g=j.result;setPending(null);setVisual(g);if(['coin','dice','rps'].includes(g.kind)){setDuel(g.kind);setMode('duel')}const animate=g.kind!=='mines'&&g.status!=='open'&&g.status!=='cancelled'&&body.move!=='cashout';if(animate){setAnimating(true);await delay(matchMedia('(prefers-reduced-motion: reduce)').matches?60:g.kind==='plinko'?2600:['dice','coin','rps'].includes(g.kind)?2100:g.kind==='blackjack'?blackjackDuration(g,active('blackjack')):g.kind==='mines'?0:650);setAnimating(false);}if(!mounted.current)return;setLocal(s=>({...s,[g.kind]:g}));setMessage(g.status==='open'?`${names[g.kind]} challenge posted.`:g.status==='cancelled'?'Challenge cancelled. Your Zs are back.':g.status==='playing'?(g.kind==='blackjack'?'Your move: hit or stand.':`${names[g.kind]} · ${az(g.payout)} ready to collect.`):g.result?.tie?(g.kind==='blackjack'?'Push. Your wager returned.':'Tie! Both wagers returned.'):g.winner_name?`@${g.winner_name} wins! ${az(g.payout)} returned.`:g.payout>0?`${names[g.kind]} · ${az(g.payout)} returned.`:`${names[g.kind]} · Better luck next time.`);onBusy(false);if(!(body.action==='move'&&g.status==='playing'))await onRefresh();}catch(e){setMessage(e.message);setRequestError(body);}finally{if(mounted.current){setBusy(false);setAnimating(false);setWaiting(null)}busyRef.current=false;onBusy(false);}}
 function confirm(body){if(!me){location.assign('/api/kick/login');return;}play({...body,requestId:crypto.randomUUID()});}
 function move(g,action,cell){play({action:'move',kind:g.kind,id:g.id,version:g.result.version,move:action,cell,requestId:crypto.randomUUID()});}
 const available=arena?.personal?.available||0;
 return <section id="vault-arcade" className="g-arcade" aria-label="Vault Arcade"><div className="g-transition"><div className="g-beam"/><span className="v-eyebrow">STEP INSIDE</span><h2>VAULT <em>ARENA</em></h2><p>Your next move starts here.</p><a href="#arcade-games" onClick={e=>{e.preventDefault();document.getElementById('arcade-games')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}} aria-label="Scroll to games">↓</a></div><div id="arcade-games"><nav className="arena-modes" aria-label="Arcade mode">{[['single','Single Player'],['duel','Head-to-Head']].map(([value,label])=><button key={value} disabled={busy} aria-pressed={mode===value} onClick={()=>setMode(value)}><span className="mode-icon" aria-hidden="true">{value==='single'?'♠':'⚔'}</span><span>{label}<small>{value==='single'?'YOUR RUN. YOUR RULES.':'PLAYER VS PLAYER'}</small></span><span className="mode-arrow" aria-hidden="true">↗</span></button>)}</nav><div className="arena-columns">
 {[[false,single,setSingle,['plinko','higher','mines','blackjack']],[true,duel,setDuel,['coin','dice','rps','open']]].filter(([isDuel])=>isDuel===(mode==='duel')).map(([isDuel,selected,setSelected,kinds])=><section className={'arena-column '+(isDuel?'arena-duels':'arena-solo')} key={isDuel?'duels':'solo'} aria-label={isDuel?'Head-to-Head games':'Single Player games'}><div className="arena-column-heading"><span className="v-eyebrow">{isDuel?'CHALLENGE THE COMMUNITY':'YOUR RUN. YOUR MOMENT.'}</span><h2>{isDuel?'HEAD-TO-HEAD / 1v1':'SINGLE PLAYER'}</h2><small>{isDuel?'Wager up to your available balance':'Maximum wager: 10 Zs'} · {az(available)} available</small></div>
 <nav className="arena-selectors" aria-label={isDuel?'Head-to-Head selector':'Single Player selector'}>{kinds.map(kind=><button key={kind} disabled={busy} aria-pressed={selected===kind} onClick={()=>setSelected(kind)}>{symbols[kind]} <span>{names[kind]}</span>{active(kind)?.status==='playing'&&<small>IN PROGRESS</small>}</button>)}</nav>
 {isDuel&&selected==='open'&&<article className="v-card g-challenges"><h3>OPEN PLAYER CHALLENGES</h3>{arena?.games?.length?arena.games.map(g=><div className="a-challenge" key={g.id}><span className="a-small-coin">{symbols[g.kind]}</span><div><strong>@{g.creator_name}</strong><p>{names[g.kind]} · {g.kind==='rps'?'CHOICE LOCKED':g.side?.toUpperCase()} · {az(g.stake)}</p></div><span>{az(g.stake*2)} <small>pot</small></span><button disabled={busy||(!g.mine&&me&&available<g.stake)} onClick={()=>g.kind==='rps'&&!g.mine&&me?setPending({action:'accept',id:g.id,stake:g.stake,kind:g.kind,requestId:crypto.randomUUID()}):confirm({action:g.mine?'cancel':'accept',id:g.id,stake:g.stake,kind:g.kind})}>{g.mine?'Cancel challenge':g.kind==='rps'?'Choose & challenge →':'Take the other side →'}</button></div>):<div className="g-empty"><span>◐</span><div><h3>THE FLOOR IS YOURS.</h3><p>Post a challenge. Another player can accept while you’re offline.</p></div></div>}</article>}
 {selected!=='open'&&<div className="arena-selected" key={selected}><Game kind={selected} game={active(selected)} visual={visual?.kind===selected?visual:null} busy={busy} animating={animating&&visual?.kind===selected} available={available} me={me} waiting={waiting} confirm={confirm} move={move}/></div>}
 </section>)}
 </div></div>
 {message&&<div className="v-alert arena-message" role="status">{message}{requestError&&<button disabled={busy} onClick={()=>play(requestError)}>Retry same request</button>}</div>}
 <article className="v-card a-recent"><h2>YOUR RECENT GAMES</h2><div className="recent-game-row recent-head"><span>Game</span><span>Wager</span><span>Result</span><span>Date</span></div>{arena?.personal?.recent?.length?arena.personal.recent.map(g=><div className="recent-game-row" key={g.id}><strong>{symbols[g.kind]} {names[g.kind]}</strong><span>{az(g.stake)}</span><span>{g.status==='playing'?'In progress':g.status==='open'?'Waiting for opponent':g.status==='cancelled'?'Cancelled':g.result?.tie?'Tie':g.is_winner?'Won':Number(g.payout)===Number(g.stake)?'Even':'Lost'}</span><small>{new Date(g.created_at).toLocaleString()}</small></div>):<p>Your game history starts with your first play.</p>}</article>
 {pending&&<Confirm pending={pending} busy={busy} onConfirm={choice=>play({...pending,...(choice?{choice}:{})})} onClose={()=>setPending(null)}/>}
 </section>
}
function Confirm({pending,busy,onConfirm,onClose}){const ref=useRef();const [choice,setChoice]=useState('rock');useEffect(()=>{const previous=document.activeElement;ref.current?.focus();const key=e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const buttons=ref.current?.querySelectorAll('button:not(:disabled)');if(!buttons?.length){e.preventDefault();return}if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[buttons.length-1].focus()}else if(!e.shiftKey&&document.activeElement===buttons[buttons.length-1]){e.preventDefault();buttons[0].focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[busy]);return <div className="a-modal-backdrop"><section ref={ref} tabIndex="-1" className="v-confirm" role="dialog" aria-modal="true" aria-labelledby="confirm-game"><h2 id="confirm-game">CHOOSE YOUR MOVE</h2><p>{pending.action==='cancel'?'Your reserved Zs will be returned if the challenge is still open.':`${az(pending.stake)} will be ${pending.action==='create'?'reserved for this challenge':'used for this game'}.`}</p>{pending.kind==='rps'&&pending.action==='accept'&&<><p>Choose privately. Both choices reveal after your wager is locked.</p><div className="a-sides">{['rock','paper','scissors'].map(c=><button type="button" key={c} disabled={busy} aria-pressed={choice===c} onClick={()=>setChoice(c)}>{c.toUpperCase()}</button>)}</div></>}<button disabled={busy} className="v-primary" onClick={()=>onConfirm(pending.kind==='rps'&&pending.action==='accept'?choice:undefined)}>{busy?'Locking in…':'Play '+az(pending.stake)+' →'}</button><button disabled={busy} onClick={onClose}>Go back</button></section></div>}
function Game({kind,game,visual,busy,animating,available,me,waiting,confirm,move}){const [choice,setChoice]=useState('rock');const isDuel=['coin','dice','rps'].includes(kind);const [stake,setStake]=useState(1),[side,setSide]=useState(kind==='dice'?'high':'heads'),[mines,setMines]=useState(3);const playing=game?.status==='playing';const shown=game;const r=shown?.result;const current=r?.card||7;const mult=Number(r?.multiplier||1);const safeCount=25-Number(r?.mines||mines)-(r?.revealed?.length||0);const tileCount=25-(r?.revealed?.length||0);const invalid=!Number.isInteger(Number(stake))||stake<1||(!isDuel&&stake>10)||(me&&available<stake);const outcome=visual?.status==='resolved'&&!animating;const effect=outcome?(visual.result?.tie||Number(visual.payout)===Number(visual.stake)?'tie':visual.isWinner?'win':'loss'):'';
 return <section id={'game-'+kind} className="g-game"><div className="g-game-title"><span>{symbols[kind]}</span><h2>{names[kind].toUpperCase()}</h2><small>{isDuel?'HEAD-TO-HEAD':kind==='plinko'?'ONE DROP. NINE POSSIBILITIES.':'PLAY YOUR NEXT MOVE'}</small></div><div className="a-game-layout"><article className={`v-card a-game-stage ${effect?'result-'+effect:''}`}>
 {kind==='blackjack'&&<Blackjack game={game} visual={visual} animating={animating}/>}
 {kind==='coin'&&<><div className={`a-coin ${animating?'g-spinning':outcome?'g-landed':''}`}><span>{outcome?visual.result.side.toUpperCase():'Z'}</span></div><h3>{animating?'IN THE AIR…':outcome?'THE COIN HAS LANDED.':'CALL YOUR SIDE.'}</h3><p>50/50 odds · Winner takes the full pot.</p></>}
 {kind==='dice'&&<><Dice values={outcome?visual.result.dice:null} rolling={animating}/><h3>{animating?'ROLLING…':'LET THE DICE TALK.'}</h3><p>Choose high or low for your die. Ties are rerolled.</p></>}
 {kind==='rps'&&<><div className={`g-rps ${animating?'facing-off':''}`}>{[0,1].map(i=><div key={i}><b>{outcome?({rock:'✊',paper:'✋',scissors:'✌'})[visual.result.choices[i]]:'?'}</b><small>{i===0?'CREATOR':'CHALLENGER'}</small></div>)}</div><h3>{animating?'ROCK. PAPER. SCISSORS…':outcome?'THE REVEAL.':'LOCK IN YOUR MOVE.'}</h3><p>Both choices stay hidden until the challenge is accepted.</p></>}
 {kind==='plinko'&&<><Board animate={animating} result={visual} sequence={visual?.id} duration="2.5s"/><h3>{animating?'WATCH IT FALL…':visual?`${visual.result.multiplier}× · ${az(visual.payout)}`:'ONE DROP. YOUR MOMENT.'}</h3></>}
 {kind==='higher'&&<><div className={`g-playing-card ${animating?'g-card-turn':''}`}><span>{animating?'?':cardName(current)}</span><b>♠</b></div><h3>{animating?'TURNING THE CARD…':playing?`CURRENT MULTIPLIER ${n(mult)}×`:'TRUST YOUR NEXT CALL.'}</h3><p>Ace is low. King is high. Equal cards lose.</p></>}
 {kind==='mines'&&<><div className="g-mine-grid">{Array.from({length:25},(_,i)=>{const revealed=r?.revealed?.includes(i);const hit=shown?.status==='resolved'&&r?.board?.includes(i);const turning=busy&&waiting?.move==='reveal'&&waiting.cell===i;return <button key={i} className={`${revealed?'revealed':''} ${hit?'mine':''} ${turning?'turning':''}`} aria-label={`Tile ${i+1}${hit?' mine':revealed?' revealed':''}`} disabled={busy||!playing||revealed} onClick={()=>move(game,'reveal',i)}>{turning?'·':hit?'✹':revealed?'◆':'◇'}</button>})}</div><h3>{animating?'REVEALING…':playing?`${n(mult)}× AND CLIMBING`:'FIND THE GEMS.'}</h3></>}
 {outcome&&<div className={`game-outcome ${effect}`} role="status"><strong>{effect==='tie'?(kind==='blackjack'?'PUSH':'TIE'):effect==='win'?'YOU WIN':'YOU LOSE'}</strong><span>{visual.result?.tie?(kind==='blackjack'?'Push. Your wager returned.':'Both wagers returned.'):isDuel?`@${visual.winner_name} takes ${az(visual.payout)}`:`${az(visual.payout)} returned`}</span></div>}
 </article><article className="v-card a-game-form"><span className="v-eyebrow">{playing?'YOUR GAME IN PROGRESS':'SET YOUR PLAY'}</span><h2>{isDuel?'CHALLENGE THE ARENA.':playing?(kind==='blackjack'?'HIT OR STAND.':'KEEP GOING OR COLLECT.'):'READY WHEN YOU ARE.'}</h2>{!playing&&<><label htmlFor={'stake-'+kind}>Wager</label><input id={'stake-'+kind} type="number" min="1" max={isDuel?undefined:10} step="1" value={stake} disabled={busy} onChange={e=>setStake(e.target.value)}/><div className="a-stakes">{(isDuel?[1,5,10,50]:[1,2,5,10]).map(v=><button key={v} disabled={busy} onClick={()=>setStake(v)}>{az(v)}</button>)}</div>{isDuel&&kind!=='rps'&&<div className="a-sides">{(kind==='coin'?['heads','tails']:['high','low']).map(s=><button key={s} disabled={busy} aria-pressed={side===s} onClick={()=>setSide(s)}>{s.toUpperCase()}</button>)}</div>}{kind==='rps'&&<div className="a-sides">{['rock','paper','scissors'].map(c=><button key={c} disabled={busy} aria-pressed={choice===c} onClick={()=>setChoice(c)}>{c.toUpperCase()}</button>)}</div>}{kind==='mines'&&<label>Mines · 1–20<input type="number" min="1" max="20" step="1" value={mines} disabled={busy} onChange={e=>setMines(Number(e.target.value))}/></label>}</>}
 {isDuel&&<p>{kind==='rps'?'Against equally likely choices: ⅓ win, ⅓ lose, ⅓ tie. A tie refunds both wagers.':'50% win chance.'} Wager {az(stake)} for a total pot of <strong>{az(Number(stake)*2)}</strong>. Cancel any time before someone accepts.</p>}
 {kind==='higher'&&playing&&<div className="g-predictions">{[['higher',13-current],['lower',current-1]].map(([direction,ways])=><button key={direction} disabled={busy||ways===0} onClick={()=>move(game,direction)}><b>{direction.toUpperCase()} {direction==='higher'?'↑':'↓'}</b><small>{(ways/13*100).toFixed(2)}% chance</small><span>{ways?az(Math.floor(Number(game.stake)*Math.min(1000,mult*.97*13/ways)*100)/100):'Unavailable'} potential return</span></button>)}</div>}
 {kind==='higher'&&!playing&&<p>Predict the next card. Each correct call increases your multiplier. You can collect between turns. Odds and the next return appear with each choice.</p>}
 {kind==='mines'&&<p>{((playing?safeCount/tileCount:(25-mines)/25)*100).toFixed(2)}% chance of a safe {playing?'next':'first'} tile. {playing?`${az(Math.floor(Number(game.stake)*(r.revealed.length?mult:.97)*tileCount/safeCount*100)/100)} potential next return.`:'Reveal gems to grow your return, then collect before hitting a mine.'}</p>}
 {kind==='blackjack'&&<><p>One shuffled 52-card deck per hand. Beat the dealer without going over 21. Aces count as 1 or 11.</p><p>Win: {az(Number(playing?game.stake:stake)*2)} · Blackjack: {az(Number(playing?game.stake:stake)*2.5)} · Push: wager returned.</p>{playing&&<p>Next hit: <strong>{(hitOdds(r.player,r.dealer).safe*100).toFixed(1)}% stay at 21 or below</strong> · {(hitOdds(r.player,r.dealer).bust*100).toFixed(1)}% bust. Based on visible cards.</p>}<p>Win odds change with the cards and your decisions. Hit or stand only; no split, double, or insurance.</p></>}
 {playing&&kind==='blackjack'?<div className="g-predictions"><button disabled={busy} onClick={()=>move(game,'hit')}>Hit +</button><button className="v-primary" disabled={busy} onClick={()=>move(game,'stand')}>Stand →</button></div>:playing?<button className="v-primary" disabled={busy} onClick={()=>move(game,'cashout')}>Collect {az(game.payout)} →</button>:<button className="v-primary" disabled={busy||invalid||(kind==='mines'&&(!Number.isInteger(mines)||mines<1||mines>20))} onClick={()=>confirm({action:isDuel?'create':kind==='plinko'?'plinko':'start',kind,stake:Number(stake),side,mines,choice})}>{busy?'Playing…':!me?'Connect to play ↗':isDuel?'Create Challenge →':kind==='plinko'?'Drop the ball ↓':'Start game →'}</button>}
 {kind==='plinko'&&<details><summary>Multipliers & odds</summary><div className="a-odds-table">{[8,2,1.5,.75,.5,.75,1.5,2,8].map((m,i)=><div key={i}><span>{m}× · {az(Number(stake)*m)}</span><span>{([1,8,28,56,70,56,28,8,1][i]/256*100).toFixed(2)}%</span></div>)}</div><p>Multipliers include the stake. Average return: 98.05%.</p></details>}
 {['mines','higher'].includes(kind)&&<details><summary>Game rules</summary><p>{kind==='mines'?'The minefield stays fixed for the entire game. Safe-tile multipliers use a 97% return factor. Reveal every safe tile to collect automatically.':'Cards are independent draws from A to K. Each successful prediction multiplies your return by 0.97 divided by its win probability. Ties lose. The game collects automatically at 1,000× or 50 successful turns.'}</p><p>Your game is saved if you leave. Return here to continue or collect.</p></details>}
 <small>{isDuel?'Minimum wager: 1 Z. No maximum beyond both players’ available Zs.':'Wagers: 1 Z to 10 Zs.'}</small></article></div></section>
}
