import React,{useState,useEffect,useRef} from 'react';
import {amountZ as az,numberZ as n} from '../server/z-format.mjs';
import {Board} from './Arena';
const names={coin:'Coin Flip',plinko:'Plinko',higher:'Higher or Lower',dice:'Dice Duel',mines:'Mines'};
const symbols={coin:'◐',plinko:'⠿',higher:'♠',dice:'⚄',mines:'◇'};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const cardName=v=>({1:'A',11:'J',12:'Q',13:'K'}[v]||v);
function Dice({values,rolling}){return <div className={`g-dice ${rolling?'rolling':''}`}>{[0,1].map(i=><div key={i} className="g-die"><span>{rolling?'⚄':['⚀','⚁','⚂','⚃','⚄','⚅'][(values?.[i]||1)-1]}</span><small>{i===0?'CREATOR':'CHALLENGER'}</small></div>)}</div>}
export default function Games({me,arena,onRefresh,onBusy}){
 const [busy,setBusy]=useState(false),[animating,setAnimating]=useState(false),[pending,setPending]=useState(null),[message,setMessage]=useState(''),[visual,setVisual]=useState(null),[local,setLocal]=useState({}),[requestError,setRequestError]=useState(null);const mounted=useRef(true);const busyRef=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;onBusy(false)}},[]);
 useEffect(()=>{if(!busy)setLocal(previous=>({...Object.fromEntries(Object.entries(previous).filter(([,g])=>g.status!=='playing')),...Object.fromEntries((arena?.active||[]).map(g=>[g.kind,g]))}))},[arena?.active]);
 const active=kind=>local[kind]||arena?.active?.find(g=>g.kind===kind);
 async function play(body){if(busyRef.current)return;busyRef.current=true;setBusy(true);onBusy(true);setMessage('');setRequestError(null);try{const r=await fetch('/api/arcade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Please try again.');const g=j.result;setPending(null);setVisual(g);const animate=g.status!=='open'&&g.status!=='cancelled'&&body.move!=='cashout';if(animate){setAnimating(true);await delay(matchMedia('(prefers-reduced-motion: reduce)').matches?60:g.kind==='plinko'?2600:g.kind==='dice'?1800:1100);setAnimating(false);}if(!mounted.current)return;setLocal(s=>({...s,[g.kind]:g}));setMessage(g.status==='open'?`${names[g.kind]} challenge posted.`:g.status==='cancelled'?'Challenge cancelled. Your Zs are back.':g.status==='playing'?`${names[g.kind]} · ${az(g.payout)} ready to collect.`:g.winner_name?`@${g.winner_name} wins! ${az(g.payout)} returned.`:g.payout>0?`${names[g.kind]} · ${az(g.payout)} returned.`:`${names[g.kind]} · Better luck next time.`);onBusy(false);await onRefresh();}catch(e){setMessage(e.message);setRequestError(body);}finally{if(mounted.current){setBusy(false);setAnimating(false)}busyRef.current=false;onBusy(false);}}
 function confirm(body){if(!me){location.assign('/api/kick/login');return;}setPending({...body,requestId:crypto.randomUUID()});}
 function move(g,action,cell){play({action:'move',id:g.id,version:g.result.version,move:action,cell,requestId:crypto.randomUUID()});}
 const available=arena?.personal?.available||0;
 return <section id="vault-arcade" className="g-arcade" aria-label="Vault Arcade"><div className="g-transition"><div className="g-beam"/><span className="v-eyebrow">STEP INSIDE</span><h2>VAULT <em>ARENA</em></h2><p>Your next move starts here.</p><a href="#arcade-games" onClick={e=>{e.preventDefault();document.getElementById('arcade-games')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}} aria-label="Scroll to games">↓</a></div><div id="arcade-games" className="v-section-heading a-arcade-heading"><div><span className="v-eyebrow">MAKE YOUR MOVE</span><h2>OPEN HEAD-TO-HEAD CHALLENGES</h2></div><div className="a-available"><small>AVAILABLE</small><strong>{az(available)}</strong></div></div>
 <article className="v-card g-challenges">{arena?.games?.length?arena.games.map(g=><div className="a-challenge" key={g.id}><span className="a-small-coin">{symbols[g.kind]}</span><div><strong>@{g.creator_name}</strong><p>{names[g.kind]} · {g.side.toUpperCase()} · {az(g.stake)}</p></div><span>{az(g.stake*2)} <small>pot</small></span><button disabled={busy||(!g.mine&&me&&available<g.stake)} onClick={()=>confirm({action:g.mine?'cancel':'accept',id:g.id,stake:g.stake,kind:g.kind})}>{g.mine?'Cancel challenge':'Take the other side →'}</button></div>):<div className="g-empty"><span>◐</span><div><h3>THE FLOOR IS YOURS.</h3><p>Create a challenge below. Someone can accept even while you’re offline.</p></div></div>}</article>
 {visual&&['coin','dice'].includes(visual.kind)&&visual.status==='resolved'&&<div className="v-card g-duel-result" aria-live="polite">{visual.kind==='dice'?<Dice values={visual.result.dice} rolling={animating}/>:<div className={`a-coin ${animating?'g-spinning':''}`}><span>{animating?'Z':visual.result.side.toUpperCase()}</span></div>}{!animating&&<h3>@{visual.winner_name} TAKES THE POT · {az(visual.payout)}</h3>}</div>}
 {message&&<div className="v-alert" role="status">{message}{requestError&&<button disabled={busy} onClick={()=>play(requestError)}>Retry same request</button>}</div>}
 <nav className="g-jump" aria-label="Arcade games">{Object.entries(names).map(([kind,label])=><a key={kind} href={'#game-'+kind} onClick={e=>{e.preventDefault();document.getElementById('game-'+kind)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}}>{symbols[kind]} {label}</a>)}</nav>
 {Object.keys(names).map(kind=><Game key={kind} kind={kind} game={active(kind)} visual={visual?.kind===kind?visual:null} busy={busy} animating={animating&&visual?.kind===kind} available={available} me={me} confirm={confirm} move={move}/>)}
 <article className="v-card a-recent"><h2>YOUR RECENT GAMES</h2>{arena?.personal?.recent?.length?arena.personal.recent.map(g=><div className="a-challenge" key={g.id}><strong>{symbols[g.kind]} {names[g.kind]}</strong><span>{az(g.stake)}</span><span>{g.status==='playing'?'In progress':g.status==='open'?'Waiting for opponent':g.status==='cancelled'?'Cancelled':g.is_winner?'Won':Number(g.payout)===Number(g.stake)?'Even':'Lost'}</span><small>{new Date(g.created_at).toLocaleString()}</small></div>):<p>Your game history starts with your first play.</p>}</article>
 {pending&&<Confirm pending={pending} busy={busy} onConfirm={()=>play(pending)} onClose={()=>setPending(null)}/>}
 </section>
}
function Confirm({pending,busy,onConfirm,onClose}){const ref=useRef();useEffect(()=>{const previous=document.activeElement;ref.current?.focus();const key=e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const buttons=ref.current?.querySelectorAll('button:not(:disabled)');if(!buttons?.length){e.preventDefault();return}if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[buttons.length-1].focus()}else if(!e.shiftKey&&document.activeElement===buttons[buttons.length-1]){e.preventDefault();buttons[0].focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[busy]);return <div className="a-modal-backdrop"><section ref={ref} tabIndex="-1" className="v-confirm" role="dialog" aria-modal="true" aria-labelledby="confirm-game"><h2 id="confirm-game">{pending.action==='cancel'?'CANCEL CHALLENGE?':`PLAY ${names[pending.kind||'plinko'].toUpperCase()}?`}</h2><p>{pending.action==='cancel'?'Your reserved Zs will be returned if the challenge is still open.':`${az(pending.stake)} will be ${pending.action==='create'?'reserved for this challenge':'used for this game'}.`}</p><button disabled={busy} className="v-primary" onClick={onConfirm}>{busy?'Working…':'Confirm'}</button><button disabled={busy} onClick={onClose}>Go back</button></section></div>}
function Game({kind,game,visual,busy,animating,available,me,confirm,move}){const [stake,setStake]=useState(1),[side,setSide]=useState(kind==='dice'?'high':'heads'),[mines,setMines]=useState(3);const playing=game?.status==='playing';const shown=game;const r=shown?.result;const current=r?.card||7;const mult=Number(r?.multiplier||1);const safeCount=25-Number(r?.mines||mines)-(r?.revealed?.length||0);const tileCount=25-(r?.revealed?.length||0);const invalid=!Number.isInteger(Number(stake))||stake<1||stake>100||(me&&available<stake);const isDuel=['coin','dice'].includes(kind);
 return <section id={'game-'+kind} className="g-game"><div className="g-game-title"><span>{symbols[kind]}</span><h2>{names[kind].toUpperCase()}</h2><small>{isDuel?'HEAD-TO-HEAD':kind==='plinko'?'ONE DROP. NINE POSSIBILITIES.':'PLAY YOUR NEXT MOVE'}</small></div><div className="a-game-layout"><article className="v-card a-game-stage">
 {kind==='coin'&&<><div className="a-coin"><span>Z</span></div><h3>CALL YOUR SIDE.</h3><p>50/50 odds · Winner takes the full pot.</p></>}
 {kind==='dice'&&<><Dice/><h3>LET THE DICE TALK.</h3><p>Choose high or low for your die. Ties are rerolled.</p></>}
 {kind==='plinko'&&<><Board result={visual} sequence={visual?.id} duration="2.5s"/><h3>{animating?'WATCH IT FALL…':visual?`${visual.result.multiplier}× · ${az(visual.payout)}`:'ONE DROP. YOUR MOMENT.'}</h3></>}
 {kind==='higher'&&<><div className={`g-playing-card ${animating?'g-card-turn':''}`}><span>{animating?'?':cardName(current)}</span><b>♠</b></div><h3>{animating?'TURNING THE CARD…':playing?`CURRENT MULTIPLIER ${n(mult)}×`:'TRUST YOUR NEXT CALL.'}</h3><p>Ace is low. King is high. Equal cards lose.</p></>}
 {kind==='mines'&&<><div className="g-mine-grid">{Array.from({length:25},(_,i)=>{const revealed=r?.revealed?.includes(i);const hit=shown?.status==='resolved'&&r?.board?.includes(i);const turning=animating&&visual?.result?.lastTile===i;return <button key={i} className={`${revealed?'revealed':''} ${hit?'mine':''} ${turning?'turning':''}`} aria-label={`Tile ${i+1}${hit?' mine':revealed?' revealed':''}`} disabled={busy||!playing||revealed} onClick={()=>move(game,'reveal',i)}>{turning?'·':hit?'✹':revealed?'◆':'◇'}</button>})}</div><h3>{animating?'REVEALING…':playing?`${n(mult)}× AND CLIMBING`:'FIND THE GEMS.'}</h3></>}
 </article><article className="v-card a-game-form"><span className="v-eyebrow">{playing?'YOUR GAME IN PROGRESS':'SET YOUR PLAY'}</span><h2>{isDuel?'CHALLENGE THE ARENA.':playing?'KEEP GOING OR COLLECT.':'READY WHEN YOU ARE.'}</h2>{!playing&&<><label htmlFor={'stake-'+kind}>Wager</label><input id={'stake-'+kind} type="number" min="1" max="100" step="1" value={stake} disabled={busy} onChange={e=>setStake(e.target.value)}/><div className="a-stakes">{[1,5,10,50].map(v=><button key={v} disabled={busy} onClick={()=>setStake(v)}>{az(v)}</button>)}</div>{isDuel&&<div className="a-sides">{(kind==='coin'?['heads','tails']:['high','low']).map(s=><button key={s} disabled={busy} aria-pressed={side===s} onClick={()=>setSide(s)}>{s.toUpperCase()}</button>)}</div>}{kind==='mines'&&<label>Mines · 1–20<input type="number" min="1" max="20" step="1" value={mines} disabled={busy} onChange={e=>setMines(Number(e.target.value))}/></label>}</>}
 {isDuel&&<p>50% win chance. Wager {az(stake)} for a total pot of <strong>{az(Number(stake)*2)}</strong>. Cancel any time before someone accepts.</p>}
 {kind==='higher'&&playing&&<div className="g-predictions">{[['higher',13-current],['lower',current-1]].map(([direction,ways])=><button key={direction} disabled={busy||ways===0} onClick={()=>move(game,direction)}><b>{direction.toUpperCase()} {direction==='higher'?'↑':'↓'}</b><small>{(ways/13*100).toFixed(2)}% chance</small><span>{ways?az(Math.floor(Number(game.stake)*Math.min(1000,mult*.97*13/ways)*100)/100):'Unavailable'} potential return</span></button>)}</div>}
 {kind==='higher'&&!playing&&<p>Predict the next card. Each correct call increases your multiplier. You can collect between turns. Odds and the next return appear with each choice.</p>}
 {kind==='mines'&&<p>{((playing?safeCount/tileCount:(25-mines)/25)*100).toFixed(2)}% chance of a safe {playing?'next':'first'} tile. {playing?`${az(Math.floor(Number(game.stake)*(r.revealed.length?mult:.97)*tileCount/safeCount*100)/100)} potential next return.`:'Reveal gems to grow your return, then collect before hitting a mine.'}</p>}
 {playing?<button className="v-primary" disabled={busy} onClick={()=>move(game,'cashout')}>Collect {az(game.payout)} →</button>:<button className="v-primary" disabled={busy||invalid||(kind==='mines'&&(!Number.isInteger(mines)||mines<1||mines>20))} onClick={()=>confirm({action:isDuel?'create':kind==='plinko'?'plinko':'start',kind,stake:Number(stake),side,mines})}>{!me?'Connect to play ↗':isDuel?'Post challenge →':kind==='plinko'?'Drop the ball ↓':'Start game →'}</button>}
 {kind==='plinko'&&<details><summary>Multipliers & odds</summary><div className="a-odds-table">{[8,2,1.5,.75,.5,.75,1.5,2,8].map((m,i)=><div key={i}><span>{m}× · {az(Number(stake)*m)}</span><span>{([1,8,28,56,70,56,28,8,1][i]/256*100).toFixed(2)}%</span></div>)}</div><p>Multipliers include the stake. Average return: 98.05%.</p></details>}
 {['mines','higher'].includes(kind)&&<details><summary>Game rules</summary><p>{kind==='mines'?'The minefield stays fixed for the entire game. Safe-tile multipliers use a 97% return factor. Reveal every safe tile to collect automatically.':'Cards are independent draws from A to K. Each successful prediction multiplies your return by 0.97 divided by its win probability. Ties lose. The game collects automatically at 1,000× or 50 successful turns.'}</p><p>Your game is saved if you leave. Return here to continue or collect.</p></details>}
 <small>Wagers: 1 Z to 100 Zs.</small></article></div></section>
}
