import React,{useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {SiKick} from 'react-icons/si';
import {FaDiscord,FaYoutube,FaTwitch,FaInstagram,FaTiktok,FaXTwitter} from 'react-icons/fa6';
import HeroMedia from '../components/HeroMedia';
import useSiteContent from '../components/useSiteContent';
import {amountZ} from '../server/z-format.mjs';
import './Home.css';
const streams=[['https://kick.com/zeekfusion',SiKick,'WATCH LIVE ON KICK','#53fc18'],['https://twitch.tv/zeekfusion',FaTwitch,'WATCH LIVE ON TWITCH','#a970ff'],['https://youtube.com/@zeekfusion',FaYoutube,'WATCH LIVE ON YOUTUBE','#ff4343']];
const socials=[['KICK','https://kick.com/zeekfusion',SiKick,'#53fc18'],['YOUTUBE','https://youtube.com/@zeekfusion',FaYoutube,'#ff4343'],['INSTAGRAM','https://instagram.com/zeekfusion',FaInstagram,'#e1306c'],['X','https://x.com/zeekfusion',FaXTwitter,'#fff'],['TIKTOK','https://tiktok.com/@zeekfusion',FaTiktok,'#fff']];
export default function Home(){const content=useSiteContent(),[status,setStatus]=useState('checking'),video=content.latestVideo;return <div className="home-page"><main className="home-layout">
<section className={'home-hero '+(status==='live'?'home-is-live':'')}><div className="hero-copy"><p className="home-eyebrow">WELCOME TO</p><h1>ZEEK<br/>FUSION</h1><p className="hero-description">IRL STREAMER. TRAVELER.<br/>CONTENT CREATOR.</p><p className="hero-tagline">CHAOS EVERYTIME.</p><div className="home-watch-stack">{streams.map(([url,Icon,label,color])=><a key={url} href={url} target="_blank" rel="noreferrer" className="home-stream-button"><Icon color={color} aria-hidden="true"/><span>{label}</span><span aria-hidden="true">→</span></a>)}</div></div><HeroMedia onStatus={setStatus}/></section>
<Link to="/map" className="home-feature home-map"><div><h2>TRAVEL MAP</h2><p>See everywhere I’ve been and where I’m going next.</p><span className="home-small-button">EXPLORE MAP →</span></div></Link>
<Link to="/market" className="home-feature home-market"><div><h2>THE Z MARKET</h2><p>Earn Zs in chat. Unlock rewards. Join the community.</p><span className="home-small-button">ENTER Z MARKET →</span></div></Link>
<section className="home-video"><h3>LATEST VIDEO</h3><a className="home-youtube" href={'https://www.youtube.com/watch?v='+video.id} target="_blank" rel="noreferrer" style={{backgroundImage:`url(https://i.ytimg.com/vi/${video.id}/hqdefault.jpg)`}}><div><span className="home-play" aria-hidden="true">▶</span><h2>{video.title}</h2></div></a><a className="home-blue-link" href={'https://www.youtube.com/watch?v='+video.id} target="_blank" rel="noreferrer">WATCH ON YOUTUBE →</a></section>
<HomeLeaders/>
<Link to="/merch" className="home-merch"><h3>MERCH</h3><h2>LIMITED DROPS<br/>COMING SOON</h2><span className="home-small-button">SHOP MERCH →</span></Link>
<section className="home-connect"><h3>CONNECT WITH ME</h3><div className="home-socials">{socials.map(([label,url,Icon,color])=><a key={label} href={url} target="_blank" rel="noreferrer"><Icon style={{color}} aria-hidden="true"/><span>{label}</span></a>)}</div><a href="https://discord.gg/AdduJ22Ven" target="_blank" rel="noreferrer" className="home-discord"><FaDiscord aria-hidden="true"/><div><strong>JOIN THE DISCORD COMMUNITY</strong><p>Hang out. Stream updates. Join the chaos.</p></div><span aria-hidden="true">↗</span></a></section>
<section className="home-stats">{[['5M+','TOTAL VIEWS'],['500+','VIDEOS'],['VISITING ALL OF USA','BY 2027'],['LIVE','ALMOST EVERY DAY'],['ALL ENERGY','ALL CHAOS']].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</section>
</main><footer className="home-footer"><span>ZEEKFUSION · ALL ENERGY. ALL CHAOS.</span><Link to="/admin">Creator admin</Link></footer></div>}
function HomeLeaders(){const [leaders,setLeaders]=useState(null),[error,setError]=useState(false);useEffect(()=>{let active=true;const load=()=>fetch('/api/arcade?balanceLeaders=1').then(r=>{if(!r.ok)throw Error();return r.json()}).then(j=>{if(active){setLeaders(j.leaders);setError(false)}}).catch(()=>{if(active)setError(true)});load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer)}},[]);return <section className="home-leaders"><span className="home-eyebrow">THE MARKET'S HEAVY HITTERS</span><h2>Z MARKET LEADERBOARD</h2><p>Most Zs in the Market. Who’s taking the crown?</p>{error?<p>Leaderboard temporarily unavailable.</p>:leaders===null?<p>Loading players…</p>:!leaders.length?<p>The first spot is waiting for you.</p>:leaders.map((u,i)=><div className={'home-leader place-'+(i+1)} key={u.username}><span>{i===0?'♛':'#'+(i+1)}</span><strong>@{u.username}</strong><b>{amountZ(u.zs_balance)}</b></div>)}<Link to="/market">ENTER THE Z MARKET →</Link></section>}
