import {translate as tr} from '../localization/language.mjs';
import React,{useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {SiKick} from 'react-icons/si';
import {FaDiscord,FaYoutube,FaTwitch,FaInstagram,FaTiktok,FaXTwitter} from 'react-icons/fa6';
import useOwnerAccess from '../components/useOwnerAccess';
import HeroMedia from '../components/HeroMedia';
import useSiteContent from '../components/useSiteContent';
import {amountZ} from '../server/z-format.mjs';
import './Home.css';
const streams=[['https://kick.com/zeekfusion',SiKick,'WATCH LIVE ON KICK','#53fc18'],['https://twitch.tv/zeekfusion',FaTwitch,'WATCH LIVE ON TWITCH','#a970ff'],['https://youtube.com/@zeekfusion',FaYoutube,'WATCH LIVE ON YOUTUBE','#ff4343']];
const socials=[['KICK','https://kick.com/zeekfusion',SiKick,'#53fc18'],['YOUTUBE','https://youtube.com/@zeekfusion',FaYoutube,'#ff4343'],['INSTAGRAM','https://instagram.com/zeekfusion',FaInstagram,'#e1306c'],['X','https://x.com/zeekfusion',FaXTwitter,'#fff'],['TIKTOK','https://tiktok.com/@zeekfusion',FaTiktok,'#fff']];
export default function Home(){const {isOwner}=useOwnerAccess();const content=useSiteContent(),[status,setStatus]=useState('checking'),video=content.latestVideo;return <div className="home-page"><main className="home-layout">
<section className={'home-hero '+(status==='live'?'home-is-live':'')}><div className="hero-copy"><p className="home-eyebrow">{tr("WELCOME TO")}</p><h1>ZEEK<br/>FUSION</h1><p className="hero-description">{tr("IRL STREAMER. TRAVELER.")}<br/>{tr("CONTENT CREATOR.")}</p><div className="home-watch-stack">{streams.map(([url,Icon,label,color])=><a key={url} href={url} target="_blank" rel="noreferrer" className="home-stream-button"><Icon color={color} aria-hidden="true"/><span>{tr(label)}</span><span aria-hidden="true">→</span></a>)}</div></div><HeroMedia onStatus={setStatus}/></section>
<Link to="/map" className="home-feature home-map"><div><h2>{tr("TRAVEL MAP")}</h2><p>{tr("See everywhere I’ve been and where I’m going next.")}</p><span className="home-small-button">{tr("EXPLORE MAP →")}</span></div></Link>
<Link to="/market" className="home-feature home-market"><div><h2>{tr("THE Z MARKET")}</h2><p>{tr("Earn Zs in chat. Unlock rewards. Join the community.")}</p><span className="home-small-button">{tr("ENTER Z MARKET →")}</span></div></Link>
<section className="home-video"><h3>{tr("LATEST VIDEO")}</h3><a className="home-youtube" href={'https://www.youtube.com/watch?v='+video.id} target="_blank" rel="noreferrer" style={{backgroundImage:`url(https://i.ytimg.com/vi/${video.id}/hqdefault.jpg)`}}><div><span className="home-play" aria-hidden="true">▶</span><h2>{video.title}</h2></div></a><a className="home-blue-link" href={'https://www.youtube.com/watch?v='+video.id} target="_blank" rel="noreferrer">{tr("WATCH ON YOUTUBE →")}</a></section>
<HomeLeaders/>
<Link to="/merch" className="home-merch"><h3>MERCH</h3><h2>LIMITED DROPS<br/>COMING SOON</h2><span className="home-small-button">SHOP MERCH →</span></Link>
<section className="home-connect"><h3>{tr("CONNECT WITH ME")}</h3><div className="home-socials">{socials.map(([label,url,Icon,color])=><a key={tr(label)} href={url} target="_blank" rel="noreferrer"><Icon style={{color}} aria-hidden="true"/><span>{tr(label)}</span></a>)}</div><a href="https://discord.gg/AdduJ22Ven" target="_blank" rel="noreferrer" className="home-discord"><FaDiscord aria-hidden="true"/><div><strong>{tr("JOIN THE DISCORD COMMUNITY")}</strong><p>{tr("Hang out. Stream updates. Join the chaos.")}</p></div><span aria-hidden="true">↗</span></a></section>
<section className="home-stats">{[['5M+','TOTAL VIEWS'],['500+','VIDEOS'],['VISIT ALL 50 U.S. STATES','BY THE END OF 2027'],['LIVE','ALMOST EVERY DAY'],['ALL ENERGY','ALL CHAOS']].map(([a,b])=><div key={a}><strong>{tr(a)}</strong><span>{tr(b)}</span></div>)}</section>
</main><footer className="home-footer"><span>ZeekFusion</span>{isOwner&&<Link to="/admin">Creator Admin</Link>}</footer></div>}
function HomeLeaders(){const [mode,setMode]=useState('current');const [leaders,setLeaders]=useState(null),[error,setError]=useState(false);useEffect(()=>{let active=true;const load=()=>fetch('/api/arcade?balanceLeaders=1&ranking='+mode).then(r=>{if(!r.ok)throw Error();return r.json()}).then(j=>{if(active){setLeaders(j.leaders);setError(false)}}).catch(()=>{if(active)setError(true)});load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer)}},[mode]);return <section className="home-leaders"><span className="home-eyebrow">{tr("THE MARKET'S HEAVY HITTERS")}</span><h2>{tr("Z MARKET LEADERBOARD")}</h2><div className="home-rank-tabs" aria-label="Leaderboard ranking">{[['current','Current Zs'],['lifetime','Lifetime Earned']].map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={()=>{if(mode!==key){setLeaders(null);setMode(key)}}}>{tr(label)}</button>)}</div><p>{tr(mode==='current'?'Most Zs available right now.':'All Zs earned, ever.')} {tr('Who’s taking the crown?')}</p>{error?<p>{tr("Leaderboard temporarily unavailable.")}</p>:leaders===null?<p>{tr("Loading players…")}</p>:!leaders.length?<p>{tr("The first spot is waiting for you.")}</p>:leaders.map((u,i)=><div className={'home-leader place-'+(i+1)} key={u.username}><span>{i===0?'♛':'#'+(i+1)}</span><strong>@{u.username}</strong><b>{amountZ(u[mode==='current'?'zs_balance':'lifetime_zs'])}</b></div>)}<Link to="/market">{tr("ENTER THE Z MARKET →")}</Link></section>}
