import React,{useEffect,useState} from 'react';
import {howDefaults} from '../server/how-it-works.mjs';
export default function HowEditor(){
 const [row,setRow]=useState(null),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){try{const r=await fetch('/api/site?admin=1');const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load content.');setRow(j);setDraft(j.content.howItWorks||structuredClone(howDefaults));setMessage('');}catch(e){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/site',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'how',revision:row.revision,howItWorks:draft})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to save.');setRow(j);window.dispatchEvent(new Event('zeek-content-changed'));setMessage('Saved. Your How It Works page is updated.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function section(index,key,value){setDraft(d=>({...d,sections:d.sections.map((s,i)=>i===index?{...s,[key]:value}:s)}));}
 return <form className="v-card" onSubmit={save}><h2>Edit How It Works</h2><p>Plain text only. Use {'{triviaReward}'}, {'{triviaMinutes}'}, {'{answerSeconds}'}, and {'{conversion}'} to keep the text in sync with your settings.</p>{draft&&<fieldset disabled={busy} className="how-editor-fields"><label>Page heading<input maxLength={160} required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Introduction<textarea maxLength={1000} value={draft.intro} onChange={e=>setDraft({...draft,intro:e.target.value})}/></label>{draft.sections.map((s,i)=><div key={i}><label>Step {i+1} title<input required maxLength={200} value={s.title} onChange={e=>section(i,'title',e.target.value)}/></label><label>Step {i+1} explanation<textarea rows={5} maxLength={4000} value={s.body} onChange={e=>section(i,'body',e.target.value)}/></label></div>)}<button disabled={busy}>{busy?'Saving…':'Save How It Works'}</button></fieldset>}{message&&<p role="status">{message}</p>}<button type="button" disabled={busy} onClick={load}>Reload saved text</button></form>;
}
