import React,{useEffect,useState,useRef} from 'react';
import {amountZ} from '../server/z-format.mjs';
async function read(kind,q,offset=0,signal){const r=await fetch(`/api/z?manage=${kind}&q=${encodeURIComponent(q)}&offset=${offset}`,{signal});const j=await r.json();if(!r.ok)throw Error(j.error||'Could not load Z management.');return j.items;}
export default function ManageZs({onChange}){
 const [query,setQuery]=useState(''),[users,setUsers]=useState([]),[selected,setSelected]=useState(null),[editing,setEditing]=useState(false),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[direction,setDirection]=useState('add'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[historyQuery,setHistoryQuery]=useState(''),[history,setHistory]=useState([]),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[userPage,setUserPage]=useState(0);const retry=useRef(null);
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>read('users',query,userPage*25,c.signal).then(setUsers).catch(e=>{if(e.name!=='AbortError')setMessage(e.message)}),250);return()=>{clearTimeout(timer);c.abort()}},[query,userPage,refresh]);
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>read('history',historyQuery,page*25,c.signal).then(setHistory).catch(e=>{if(e.name!=='AbortError')setMessage(e.message)}),250);return()=>{clearTimeout(timer);c.abort()}},[historyQuery,page,refresh]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setMessage('');const input={action:'adjust',userId:Number(selected.kick_user_id),username:selected.username,amount:Number(amount)*(direction==='subtract'?-1:1),reason:reason.trim()};const fingerprint=JSON.stringify(input);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,body:{...input,requestId:crypto.randomUUID()}};try{const r=await fetch('/api/z',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(retry.current.body)});const j=await r.json();if(!r.ok)throw Error(j.error||'Adjustment failed.');setSelected(j.result);setUsers(old=>old.map(u=>u.kick_user_id===j.result.kick_user_id?j.result:u));setEditing(false);setAmount('');setReason('');retry.current=null;setMessage(`Saved. @${j.result.username} now has ${amountZ(j.result.zs_balance)}.`);setRefresh(x=>x+1);await onChange();}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="v-card manage-zs"><span className="v-eyebrow">OWNER CONTROLS</span><h2>MANAGE Zs</h2><label>Search Kick username<input value={query} onChange={e=>{setQuery(e.target.value);setUserPage(0)}} placeholder="Search a player…" maxLength="100"/></label><div className="manage-users">{users.map(u=><button key={u.kick_user_id} disabled={busy} aria-pressed={selected?.kick_user_id===u.kick_user_id} onClick={()=>{setSelected(u);setEditing(false);setMessage('');retry.current=null}}><strong>@{u.username}</strong><span>{amountZ(u.zs_balance)}</span><small>{amountZ(u.lifetime_zs)} lifetime earned</small></button>)}{!users.length&&<p>No matching players.</p>}</div><div className="manage-pages"><button disabled={!userPage||busy} onClick={()=>setUserPage(x=>x-1)}>Previous users</button><button disabled={users.length<25||busy} onClick={()=>setUserPage(x=>x+1)}>More users</button></div>
 {selected&&<div className="manage-selected"><h3>@{selected.username}</h3><div className="manage-totals"><div><small>CURRENT BALANCE</small><strong>{amountZ(selected.zs_balance)}</strong></div><div><small>LIFETIME EARNED</small><strong>{amountZ(selected.lifetime_zs)}</strong></div></div>{!editing?<button className="v-primary" onClick={()=>setEditing(true)}>Edit Zs</button>:<form onSubmit={save}><div className="a-sides"><button type="button" disabled={busy} aria-pressed={direction==='add'} onClick={()=>setDirection('add')}>Add Zs</button><button type="button" disabled={busy} aria-pressed={direction==='subtract'} onClick={()=>setDirection('subtract')}>Subtract Zs</button></div><label>Amount<input type="number" min="0.01" step="0.01" required value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label>Short reason<input minLength="3" maxLength="300" required value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><button className="v-primary" disabled={busy}>{busy?'Saving…':'Save adjustment'}</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button><p>Adding Zs increases lifetime earned. Subtracting Zs changes the current balance only.</p></form>}</div>}
 {message&&<p className="v-alert" role="status">{message}</p>}<h3>MANUAL ADJUSTMENT HISTORY</h3><label>Search history by username or reason<input value={historyQuery} maxLength="100" onChange={e=>{setHistoryQuery(e.target.value);setPage(0)}}/></label><div className="manage-history">{history.map(h=><article key={h.id}><div><strong>@{h.username}</strong><b>{Number(h.amount)>0?'+':''}{amountZ(h.amount)}</b></div><p>{h.reason}</p><small>{new Date(h.created_at).toLocaleString()}{h.balance_after!==null&&` · Balance after: ${amountZ(h.balance_after)}`}</small></article>)}{!history.length&&<p>No matching adjustments.</p>}</div><div className="manage-pages"><button disabled={!page} onClick={()=>setPage(x=>x-1)}>Previous adjustments</button><button disabled={history.length<25} onClick={()=>setPage(x=>x+1)}>More adjustments</button></div></section>
}
