import React,{useEffect,useState,useCallback} from 'react';
import {Link} from 'react-router-dom';
import './Vault.css';
const z=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(n||0));
const date=x=>x?new Date(x).toLocaleString(): '—';
async function request(body){const r=await fetch('/api/z',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Please try again.');return j;}
export default function Vault(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('Overview'),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[confirmReward,setConfirmReward]=useState(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/z');const j=await r.json();if(!r.ok)throw new Error(j.error||'The Vault is temporarily unavailable.');setData(j);setError('');}catch(e){setError(e.message);}},[]);
 useEffect(()=>{load();const poll=setInterval(load,15000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(clock);};},[load]);
 async function act(body,message){setBusy(true);setNotice('');try{await request(body);setNotice(message||'Saved.');await load();setConfirmReward(null);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 const me=data?.me,cfg=data?.settings||{},live=data?.runtime?.is_live,round=data?.round,open=round?.status==='open'&&Date.parse(round.expires_at)>now;
 const remaining=open?Math.max(0,Math.ceil((Date.parse(round.expires_at)-now)/1000)):live&&data?.runtime?.next_question_at?Math.max(0,Math.ceil((Date.parse(data.runtime.next_question_at)-now)/60000)):null;
 return <div className="vault"><header className="v-nav"><Link to="/" className="v-brand">ZEEK<span>FUSION</span><small>THE Z VAULT</small></Link><nav><Link to="/">Home</Link><Link to="/map">Travel map</Link><a href="https://kick.com/zeekfusion" target="_blank" rel="noreferrer">Watch live ↗</a></nav>{me?<button onClick={()=>act({action:'logout'},'Logged out.')}>@{me.username} · Log out</button>:<a className="v-button v-login" href="/api/kick/login">Connect with Kick ↗</a>}</header>
 <main className="v-main"><section className="v-hero"><div><div className="v-eyebrow"><span className={live?'v-dot live':'v-dot'}></span>{live?'LIVE ON KICK':'THE COMMUNITY NEVER CLOCKS OUT'}</div><h1>Good moments.<br/><em>Real bragging rights.</em></h1><p>Win questions. Support the stream. Stack your Zs.<br/>This is your place in the ZeekFusion community.</p><a href="https://kick.com/zeekfusion" className="v-button v-primary" target="_blank" rel="noreferrer">Join the chat ↗</a></div><div className="v-balance"><div className="v-eyebrow">{me?'YOUR VAULT':'YOUR NEXT CHAPTER'}</div><div className="v-balance-number">{me?z(me.zs_balance):'Z'}<span>{me?'Zs':'s'}</span></div><p>{me?`${z(me.lifetime_zs)} Zs earned all time`:'Earn in chat. Your balance follows you here.'}</p>{!me&&<a href="/api/kick/login">See your balance →</a>}<div className="v-balance-lines" aria-hidden="true"></div></div></section>
 <div className="v-tabs" role="tablist" aria-label="Vault sections">{['Overview','Rewards','Giveaways','My activity',...(me?.isAdmin?['Controls']:[])].map(t=><button role="tab" aria-selected={t===tab} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {error&&<div className="v-alert" role="alert">{error} <button onClick={load}>Retry</button></div>}{notice&&<div className="v-alert" role="status">{notice}</div>}
 {!data&&!error&&<p className="v-loading">Opening the Vault…</p>}
 {data&&tab==='Overview'&&<><section className="v-grid"><article className="v-card v-question"><div className="v-row"><span className="v-eyebrow">⚡ Z QUESTIONS</span><span className="v-pill">+{z(cfg.question_z)} Z</span></div><h2>{open?round.question:live?'Eyes on the chat.':'Catch the next live stream.'}</h2><p>{open?`Answer in Kick chat. ${remaining}s remaining.`:live?`Next question ${remaining===0?'is coming up':remaining===null?'during the stream':`in about ${remaining} min`}.`:`A new question every ${cfg.question_interval_minutes} minutes while Zeek is live.`}</p><p className="v-muted">First correct answer received wins. No website login needed to earn.</p>{round?.winner_username&&<div className="v-winner">Last winner <strong>@{round.winner_username}</strong> <span>+{z(round.reward)} Zs</span></div>}</article><article className="v-card"><span className="v-eyebrow">HOW TO STACK Zs</span><h2>Show up. Get involved.</h2><div className="v-rate"><span>Win a Z Question</span><strong>+{z(cfg.question_z)} Zs</strong></div><div className="v-rate"><span>Subscribe or renew</span><strong>+{z(cfg.subscription_z)} / +{z(cfg.renewal_z)} Zs</strong></div><div className="v-rate"><span>Gift a subscription</span><strong>+{z(cfg.gift_z)} Zs each</strong></div>{cfg.kicks_enabled&&<div className="v-rate"><span>Send {cfg.kicks_per_z} KICKs</span><strong>+1 Z</strong></div>}<p className="v-muted">Your Zs are community points with no cash value. Type <b>!zs</b> in chat to check your balance.</p></article></section>
 <section className="v-grid"><article className="v-card"><div className="v-row"><h2>The leaderboard</h2><span className="v-muted">All-time Zs</span></div>{!data.leaderboard.length?<p>The first chapter starts in chat.</p>:data.leaderboard.map((u,i)=><div className="v-leader" key={u.username}><span className={i<3?'v-rank top':'v-rank'}>{String(i+1).padStart(2,'0')}</span><strong>@{u.username}</strong><span>{z(u.lifetime_zs)} <small>Zs</small></span></div>)}</article><article className="v-card"><h2>Around the Vault</h2>{data.feed.length?data.feed.map((e,i)=><div className="v-feed" key={i}><div><strong>@{e.z_users?.username||'Viewer'}</strong><p>{e.reason}</p><small>{date(e.created_at)}</small></div><span>+{z(e.amount)} Zs</span></div>):<p>Community wins will appear here.</p>}</article></section></>}
 {data&&tab==='Rewards'&&<><div className="v-section-heading"><h2>Put your Zs to work.</h2><p>Choose a reward. Zeek will handle the rest.</p></div><div className="v-reward-grid">{data.rewards.length?data.rewards.map(r=><article className="v-card" key={r.id}><span className="v-eyebrow">STREAM REWARD</span><h2>{r.title}</h2><p>{r.description}</p><div className="v-row"><strong className="v-price">{z(r.cost)} Zs</strong><small>{r.stock===null?'':`${r.stock} left`}</small></div><button className="v-primary" disabled={busy||r.stock===0||(me&&Number(me.zs_balance)<Number(r.cost))} onClick={()=>me?setConfirmReward({...r,requestId:crypto.randomUUID()}):location.assign('/api/kick/login')}>{!me?'Connect to redeem':r.stock===0?'Sold out':Number(me.zs_balance)<Number(r.cost)?'Keep stacking Zs':'Redeem →'}</button></article>):<article className="v-card"><h2>The shelf is getting ready.</h2><p>Zeek will add rewards here. Your Zs stay in your Vault until you choose to use them.</p></article>}</div>{confirmReward&&<div className="v-confirm" role="dialog" aria-modal="true" aria-label="Confirm redemption"><h2>Redeem {confirmReward.title}?</h2><p>This uses {z(confirmReward.cost)} Zs from your balance.</p><button disabled={busy} className="v-primary" onClick={()=>act({action:'redeem',rewardId:confirmReward.id,requestId:confirmReward.requestId},'Reward requested! Follow its progress in My activity.')}>Confirm redemption</button><button disabled={busy} onClick={()=>setConfirmReward(null)}>Cancel</button></div>}</>}
 {data&&tab==='Giveaways'&&<><div className="v-section-heading"><h2>A little luck. A lot of community.</h2><p>One free entry per Kick account. No Zs or purchase needed.</p></div><div className="v-reward-grid">{data.giveaways.length?data.giveaways.map(g=><article className="v-card" key={g.id}><span className="v-eyebrow">COMMUNITY GIVEAWAY</span><h2>{g.title}</h2><p>{g.description}</p><p>Entries close {date(g.closes_at)}</p>{g.status==='drawn'?<p className="v-winner">Winner: @{g.winner_username}</p>:<button disabled={busy||Date.parse(g.closes_at)<now||me?.entries.some(e=>e.giveaway_id===g.id)} onClick={()=>me?act({action:'enter',id:g.id},'You’re entered!'):location.assign('/api/kick/login')}>{me?.entries.some(e=>e.giveaway_id===g.id)?'You’re in ✓':Date.parse(g.closes_at)<now?'Entries closed':'Enter free →'}</button>}</article>):<article className="v-card"><h2>Nothing open just yet.</h2><p>Watch the stream for the next community giveaway.</p></article>}</div></>}
 {data&&tab==='My activity'&&(!me?<article className="v-card"><h2>Your story is already being counted.</h2><p>Connect the Kick account you use in chat to see your Zs.</p><a className="v-button v-primary" href="/api/kick/login">Connect with Kick</a></article>:<><section className="v-grid"><article className="v-card"><h2>Your Z history</h2>{me.history.length?me.history.map((e,i)=><div className="v-feed" key={i}><div><strong>{e.reason}</strong><p>{date(e.created_at)}</p></div><span>{Number(e.amount)>0?'+':''}{z(e.amount)} Zs</span></div>):<p>Your first Z is waiting in chat.</p>}</article><article className="v-card"><h2>Your rewards</h2>{me.redemptions.length?me.redemptions.map(r=><div className="v-feed" key={r.id}><div><strong>{r.title}</strong><p>{r.status}</p></div><span>{z(r.cost)} Zs</span></div>):<p>You haven’t redeemed a reward yet.</p>}<h2>BotRix conversions</h2>{cfg.botrix_enabled?<form onSubmit={e=>{e.preventDefault();act({action:'convert',points:Number(new FormData(e.currentTarget).get('points')),requestId:crypto.randomUUID()},'Conversion ticket submitted for review.');}}><p>{cfg.botrix_points_per_z} BotRix points → 1 Z. Up to {z(cfg.botrix_weekly_cap_z)} Zs per week. A moderator checks and deducts your BotRix points before approval.</p><label>BotRix points<input name="points" type="number" min={cfg.botrix_points_per_z} step={cfg.botrix_points_per_z} required/></label><button disabled={busy}>Submit ticket</button></form>:<p>Conversions aren’t open yet. Keep using your BotRix points as usual.</p>}{me.tickets.map(t=><p key={t.id}>{t.points} points → {z(t.zs)} Zs · {t.status}</p>)}</article></section></>)}
 {data&&tab==='Controls'&&me?.isAdmin&&<Controls onChange={load}/>}
 <footer className="v-footer"><span>ZEEKFUSION · THE Z VAULT</span><span>Earned in the moment. Kept in the Vault.</span></footer></main></div>;
}
function Controls({onChange}){
 const [a,setA]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[selectedReward,setSelectedReward]=useState(null),[selectedQuestion,setSelectedQuestion]=useState(null);
 const reload=useCallback(async()=>{const r=await fetch('/api/z?admin=1');const j=await r.json();if(!r.ok)throw new Error(j.error);setA(j);},[]);
 useEffect(()=>{reload().catch(e=>setMsg(e.message));},[reload]);
 async function save(body){setBusy(true);setMsg('');try{const j=await request(body);setMsg(j.result?.username?`Winner: @${j.result.username}`:'Saved.');await reload();await onChange();}catch(e){setMsg(e.message);}finally{setBusy(false);}}
 function form(e,action){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));save({action,...f});}
 if(!a)return <p>{msg||'Loading your controls…'}</p>;
 const labels={subscription_z:'New subscription · Zs',gift_z:'Each gifted subscription · Zs',renewal_z:'Renewal · Zs',question_z:'Question winner · Zs',question_interval_minutes:'Minutes between questions',answer_seconds:'Seconds to answer',kicks_per_z:'KICKs for 1 Z',botrix_points_per_z:'BotRix points for 1 Z',botrix_weekly_cap_z:'Weekly BotRix conversion cap · Zs'};
 return <div className="v-controls"><div className="v-card"><div className="v-row"><div><h2>Your stream, your rules.</h2><p>Rates apply to new earnings. Existing balances stay the same.</p></div><a className="v-button v-primary" href="/api/kick/login?bot=1">{a.botConnected?'Reconnect Kick bot':'Activate Kick bot'} ↗</a></div><p>{a.botConnected?'Kick bot connected.':'Connect the ZeekFusion Kick account to let the bot post questions and balance replies.'} Last timer check: {date(a.runtime.checked_at)}</p>{a.runtime.bot_error&&<p role="alert" className="v-alert">{a.runtime.bot_error}</p>}<button disabled={busy} onClick={()=>save({action:'tick'})}>Check live status now</button>{msg&&<p className="v-alert" role="status">{msg}</p>}</div>
 <form className="v-card" key={JSON.stringify(a.settings)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),settings={};for(const k of Object.keys(labels))settings[k]=Number(f.get(k));for(const k of ['questions_enabled','kicks_enabled','botrix_enabled'])settings[k]=f.has(k);save({action:'settings',settings});}}><h2>Earning rates & timing</h2><div className="v-form-grid">{Object.entries(labels).map(([k,l])=><label key={k}>{l}<input name={k} defaultValue={a.settings[k]} type="number" step={k.endsWith('_z')?'0.01':'1'} min="0" required/></label>)}</div><div className="v-checks">{[['questions_enabled','Automatic questions while live'],['kicks_enabled','Award Zs for KICKs'],['botrix_enabled','Accept BotRix conversion tickets']].map(([k,l])=><label key={k}><input type="checkbox" name={k} defaultChecked={a.settings[k]}/>{l}</label>)}</div><button className="v-primary" disabled={busy}>Save settings</button></form>
 <section className="v-grid"><form className="v-card" key={'q'+selectedQuestion?.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'question',id:selectedQuestion?.id,question:f.get('question'),answers:f.get('answers'),category:f.get('category'),enabled:f.has('enabled')});}}><h2>{selectedQuestion?'Edit question':'Add a question'}</h2><label>Question<textarea name="question" maxLength="260" defaultValue={selectedQuestion?.question||''} required/></label><label>Accepted answers · separate alternatives with |<input name="answers" defaultValue={selectedQuestion?.answers.join(' | ')||''} required/></label><label>Category<input name="category" defaultValue={selectedQuestion?.category||'Stream'}/></label><label className="v-check"><input type="checkbox" name="enabled" defaultChecked={selectedQuestion?.enabled??true}/>Enabled</label><button disabled={busy}>Save question</button>{selectedQuestion&&<button type="button" onClick={()=>setSelectedQuestion(null)}>New question</button>}<details><summary>{a.questions.length} questions in the bank</summary><div className="v-scroll">{a.questions.map(q=><button type="button" className="v-list-button" key={q.id} onClick={()=>setSelectedQuestion(q)}>{q.enabled?'●':'○'} {q.question}</button>)}</div></details></form>
 <form className="v-card" key={'r'+selectedReward?.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'reward',id:selectedReward?.id,title:f.get('title'),description:f.get('description'),cost:Number(f.get('cost')),stock:f.get('stock')===''?null:Number(f.get('stock')),enabled:f.has('enabled')});}}><h2>{selectedReward?'Edit reward':'Add a reward'}</h2><label>Title<input name="title" maxLength="80" defaultValue={selectedReward?.title||''} required/></label><label>Description<textarea name="description" defaultValue={selectedReward?.description||''}/></label><label>Cost in Zs<input name="cost" type="number" min="0.01" step="0.01" defaultValue={selectedReward?.cost||5} required/></label><label>Stock · blank for unlimited<input name="stock" type="number" min="0" step="1" defaultValue={selectedReward?.stock??''}/></label><label className="v-check"><input type="checkbox" name="enabled" defaultChecked={selectedReward?.enabled||false}/>Available to viewers</label><button disabled={busy}>Save reward</button>{selectedReward&&<button type="button" onClick={()=>setSelectedReward(null)}>New reward</button>}<details><summary>{a.rewards.length} rewards</summary>{a.rewards.map(r=><button type="button" className="v-list-button" key={r.id} onClick={()=>setSelectedReward(r)}>{r.enabled?'●':'○'} {r.title} · {z(r.cost)} Zs</button>)}</details></form></section>
 <section className="v-grid"><article className="v-card"><h2>Reward requests</h2>{a.redemptions.length?a.redemptions.map(r=><div className="v-request" key={r.id}><strong>{r.title}</strong><p>Kick ID {r.kick_user_id} · {z(r.cost)} Zs · {r.status}</p>{r.status==='pending'&&<><button disabled={busy} onClick={()=>save({action:'redemption',id:r.id,status:'fulfilled'})}>Mark fulfilled</button><button disabled={busy} onClick={()=>save({action:'redemption',id:r.id,status:'refunded'})}>Refund Zs</button></>}</div>):<p>No requests yet.</p>}</article><article className="v-card"><h2>BotRix tickets</h2><p>Deduct points in BotRix first, then record the deduction here. Approving awards Zs; it does not deduct BotRix points automatically.</p>{a.tickets.length?a.tickets.map(t=><form className="v-request" key={t.id} onSubmit={e=>{e.preventDefault();save({action:'conversion',id:t.id,status:'approved',proof:new FormData(e.currentTarget).get('proof')});}}><strong>Kick ID {t.kick_user_id}</strong><p>{t.points} points → {z(t.zs)} Zs · {t.status}</p>{t.status==='pending'&&<><label>Deduction confirmation<input name="proof" minLength="5" placeholder="Deducted in BotRix on…" required/></label><button disabled={busy}>Approve & award Zs</button><button type="button" disabled={busy} onClick={()=>save({action:'conversion',id:t.id,status:'rejected',proof:''})}>Reject</button></>}</form>):<p>No tickets yet.</p>}</article></section>
 <section className="v-grid"><form className="v-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'adjust',userId:Number(f.get('userId')),username:f.get('username'),amount:Number(f.get('amount')),reason:f.get('reason'),requestId:crypto.randomUUID()});}}><h2>Adjust a balance</h2><p>For corrections and special stream challenges. Every adjustment is recorded.</p><label>Kick user ID<input name="userId" type="number" required/></label><label>Kick username<input name="username" required/></label><label>Zs to add or deduct<input name="amount" type="number" step="0.01" required/></label><label>Reason<input name="reason" minLength="3" required/></label><button disabled={busy}>Record adjustment</button></form>
 <form className="v-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'giveaway',title:f.get('title'),description:f.get('description'),closesAt:f.get('closesAt'),enabled:f.has('enabled')});}}><h2>Create a giveaway</h2><p>Free entry, one per Kick account. Add the prize, eligibility, and rules in the description.</p><label>Title<input name="title" required/></label><label>Description & rules<textarea name="description" required/></label><label>Entries close<input name="closesAt" type="datetime-local" required/></label><label className="v-check"><input name="enabled" type="checkbox"/>Open entries immediately</label><button disabled={busy}>Create giveaway</button>{a.giveaways.map(g=><div className="v-request" key={g.id}><strong>{g.title}</strong><p>{g.status}{g.winner_username?` · Winner @${g.winner_username}`:''}</p>{g.status==='draft'&&<button type="button" disabled={busy||Date.parse(g.closes_at)<Date.now()} onClick={()=>save({action:'publish-giveaway',id:g.id})}>Open free entries</button>}{g.status==='open'&&Date.parse(g.closes_at)<Date.now()&&<button type="button" disabled={busy} onClick={()=>{if(window.confirm(`Draw one winner for ${g.title}? This result will be final.`))save({action:'draw',id:g.id});}}>Draw winner</button>}</div>)}</form></section>
 {a.failures.length>0&&<article className="v-card"><h2>Chat delivery needs attention</h2><p>These messages were not confirmed. They are not automatically resent, to avoid duplicate posts.</p>{a.failures.map(f=><p key={f.id}>{f.content} · {f.status}</p>)}</article>}<details className="v-card"><summary>Recent owner actions</summary>{a.log.map(l=><p key={l.id}>{date(l.created_at)} · {l.action}</p>)}</details></div>;
}
