import React,{useEffect,useState,useCallback,useRef} from 'react';
import './Vault.css';
import './Arena.css';
import Games from './Games';
import ManageZs from './ManageZs';
import SocialConnections from './SocialConnections';
import {amountZ} from '../server/z-format.mjs';
import './Games.css';
import {Dashboard,TopPlayers,CommunityFeed,Leaderboard,AllActivity} from './Arena';
const z=amountZ;
const date=x=>x?new Date(x).toLocaleString(): '—';
async function request(body){const r=await fetch('/api/z',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Please try again.');return j;}
export default function Vault(){
 const animation=useRef(false);const [scrollArcade,setScrollArcade]=useState(false);
 function goArcade(){setTab('Overview');setScrollArcade(true)}
 useEffect(()=>{if(scrollArcade){document.getElementById('vault-arcade')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setScrollArcade(false)}},[scrollArcade]);
 const [arena,setArena]=useState(null),[arenaError,setArenaError]=useState(''),[feedFilter,setFeedFilter]=useState('All');
 const loadArena=useCallback(async()=>{try{if(animation.current)return;const r=await fetch('/api/arcade');const j=await r.json();if(!r.ok)throw new Error(j.error||'The Arcade is temporarily unavailable.');if(!animation.current)setArena(j);setArenaError('');}catch(e){setArenaError(e.message);}},[]);
 useEffect(()=>{loadArena();const t=setInterval(loadArena,15000);return()=>clearInterval(t);},[loadArena]);
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState(location.hash.includes('connections=1')?'Controls':'Overview'),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[confirmReward,setConfirmReward]=useState(null);
 const load=useCallback(async()=>{try{if(animation.current)return;const r=await fetch('/api/z');const j=await r.json();if(!r.ok)throw new Error(j.error||'The Z Market is temporarily unavailable.');if(!animation.current)setData(j);setError('');}catch(e){setError(e.message);}},[]);
 useEffect(()=>{load();const poll=setInterval(load,15000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(clock);};},[load]);
 async function act(body,message){setBusy(true);setNotice('');try{await request(body);setNotice(message||'Saved.');await load();setConfirmReward(null);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 const me=data?.me,cfg=data?.settings||{},live=data?.runtime?.is_live,round=data?.round,open=round?.status==='open'&&Date.parse(round.expires_at)>now;
 const remaining=open?Math.max(0,Math.ceil((Date.parse(round.expires_at)-now)/1000)):live&&data?.runtime?.next_question_at?Math.max(0,Math.ceil((Date.parse(data.runtime.next_question_at)-now)/60000)):null;
 return <div className="vault"><main className="v-main"><div className="a-section-bar"><span>THE Z MARKET <span>/ COMMUNITY ARENA</span></span>{me?<button onClick={()=>act({action:'logout'},'Logged out.').then(loadArena)}>@{me.username} · Log out</button>:<a href="/api/kick/login">Connect with Kick ↗</a>}</div>
 {tab==='Overview'&&<><Dashboard me={me} personal={arena?.personal} live={live} onArcade={goArcade} onHow={()=>setTab('How It Works')}/><TopPlayers players={arena?.leaders||data?.leaderboard||[]} onFull={()=>setTab('Leaderboard')}/></>}
 <div className="v-tabs" role="tablist" aria-label="Market sections">{['Overview','Arcade','Leaderboard','Activity','Rewards','Giveaways','How It Works','My activity',...(me?.isAdmin?['Controls']:[])].map(t=><button role="tab" aria-selected={t===tab} key={t} onClick={()=>t==='Arcade'?goArcade():setTab(t)}>{t}</button>)}</div>
 {error&&<div className="v-alert" role="alert">{error} <button onClick={load}>Retry</button></div>}{notice&&<div className="v-alert" role="status">{notice}</div>}
 {!data&&!error&&<p className="v-loading">Opening the Market…</p>}
 {arenaError&&<div className="v-alert" role="alert">{arenaError} <button onClick={loadArena}>Retry Arcade</button></div>}
 {data&&tab==='Overview'&&<section className="a-home-grid"><CommunityFeed items={arena?.feed||[]} filter={feedFilter} setFilter={setFeedFilter} limit={5} onFull={()=>setTab('Activity')}/><aside><article className="v-card v-question"><div className="v-row"><span className="v-eyebrow">ϟ LIVE TRIVIA</span><span className="v-pill">+{z(cfg.question_z)}</span></div><h2>{open?round.question:live?'READY FOR THE NEXT ONE?':'THE CHAT IS YOUR STARTING LINE.'}</h2><p>{open?`Answer in Kick chat. ${remaining}s remaining.`:live?`Next question ${remaining===0?'is coming up':remaining===null?'during the stream':`in about ${remaining} min`}.`:'Trivia returns when Zeek goes live.'}</p>{round?.winner_username&&<div className="v-winner">Last winner <strong>@{round.winner_username}</strong><span>+{z(round.reward)}</span></div>}<a className="v-button v-primary" href="https://kick.com/zeekfusion" target="_blank" rel="noreferrer">Jump into chat ↗</a></article><button className="a-help-link" onClick={()=>setTab('How It Works')}>New here? How It Works →</button></aside></section>}
 {data&&tab==='Overview'&&<Games me={me} arena={arena} onBusy={value=>{animation.current=value}} onRefresh={()=>Promise.all([load(),loadArena()])}/>}
 {data&&tab==='Activity'&&<AllActivity/>}
 {data&&tab==='Leaderboard'&&<Leaderboard players={arena?.leaders||data.leaderboard}/>}
 {data&&tab==='How It Works'&&<><div className="v-section-heading"><div className="v-eyebrow">THE RULES OF THE ARENA</div><h2>SHOW UP. STACK Zs. JOIN IN.</h2><p>Win trivia, play games, and unlock your next stream interaction.</p></div><div className="v-reward-grid"><article className="v-card"><span className="v-eyebrow">01 / EARN</span><h2>Answer trivia questions in Zeek’s chat to earn Zs.</h2><p>The first correct trivia answer wins {z(cfg.question_z)}. Questions run every {cfg.question_interval_minutes} minutes while live, with {cfg.answer_seconds} seconds to answer.</p><p>Type <b>!zs</b> in Kick chat to see your balance. </p></article><article className="v-card"><span className="v-eyebrow">02 / UNLOCK</span><h2>Use Zs to unlock stream interactions and forfeits.</h2><p>Spend Zs on stream interactions. </p><p>A moderator deducts your BotRix points and approves the conversion.</p><p>{Number(cfg.botrix_points_per_z).toLocaleString()} BotRix points → 1 Z.</p><button onClick={()=>setTab('My activity')}>Request a conversion →</button></article><article className="v-card"><span className="v-eyebrow">03 / PLAY</span><h2>Play Arcade games to risk your Zs and win more.</h2><p>Coin Flip reserves your wager until another player accepts or you cancel. Both sides have a 50% chance. The winner receives the full pot, including their stake.</p><p>Plinko uses eight independent turns generated on the server. Check every multiplier and its odds in the Arcade before playing.</p></article></div></>}
 {data&&tab==='Rewards'&&<><div className="v-section-heading"><h2>Put your Zs to work.</h2><p>Unlock a stream interaction. Zeek will handle the rest.</p></div><div className="v-reward-grid">{data.rewards.length?data.rewards.map(r=><article className="v-card" key={r.id}><span className="v-eyebrow">STREAM REWARD</span><h2>{r.title}</h2><p>{r.description}</p><div className="v-row"><strong className="v-price">{z(r.cost)}</strong><small>{r.stock===null?'':`${r.stock} left`}</small></div><button className="v-primary" disabled={busy||r.stock===0||(me&&Number(me.zs_balance)<Number(r.cost))} onClick={()=>me?setConfirmReward({...r,requestId:crypto.randomUUID()}):location.assign('/api/kick/login')}>{!me?'Connect to redeem':r.stock===0?'Sold out':Number(me.zs_balance)<Number(r.cost)?'Keep stacking Zs':'Redeem →'}</button></article>):<article className="v-card"><h2>The shelf is getting ready.</h2><p>Zeek will add rewards here. Your Zs stay in your Market until you choose to use them.</p></article>}</div>{confirmReward&&<div className="v-confirm" role="dialog" aria-modal="true" aria-label="Confirm redemption"><h2>Redeem {confirmReward.title}?</h2><p>This uses {z(confirmReward.cost)} from your balance.</p><button disabled={busy} className="v-primary" onClick={()=>act({action:'redeem',rewardId:confirmReward.id,requestId:confirmReward.requestId},'Reward requested! Follow its progress in My activity.')}>Confirm redemption</button><button disabled={busy} onClick={()=>setConfirmReward(null)}>Cancel</button></div>}</>}
 {data&&tab==='Giveaways'&&<><div className="v-section-heading"><h2>A little luck. A lot of community.</h2><p>One entry per Kick account.</p></div><div className="v-reward-grid">{data.giveaways.length?data.giveaways.map(g=><article className="v-card" key={g.id}><span className="v-eyebrow">COMMUNITY GIVEAWAY</span><h2>{g.title}</h2><p>{g.description}</p><p>Entries close {date(g.closes_at)}</p>{g.status==='drawn'?<p className="v-winner">Winner: @{g.winner_username}</p>:<button disabled={busy||Date.parse(g.closes_at)<now||me?.entries.some(e=>e.giveaway_id===g.id)} onClick={()=>me?act({action:'enter',id:g.id},'You’re entered!'):location.assign('/api/kick/login')}>{me?.entries.some(e=>e.giveaway_id===g.id)?'You’re in ✓':Date.parse(g.closes_at)<now?'Entries closed':'Enter →'}</button>}</article>):<article className="v-card"><h2>Nothing open just yet.</h2><p>Watch the stream for the next community giveaway.</p></article>}</div></>}
 {data&&tab==='My activity'&&(!me?<article className="v-card"><h2>Your story is already being counted.</h2><p>Connect the Kick account you use in chat to see your Zs.</p><a className="v-button v-primary" href="/api/kick/login">Connect with Kick</a></article>:<><section className="v-grid"><article className="v-card"><h2>Your Z history</h2>{me.history.length?me.history.map((e,i)=><div className="v-feed" key={i}><div><strong>{e.reason}</strong><p>{date(e.created_at)}</p></div><span>{Number(e.amount)>0?'+':''}{z(e.amount)}</span></div>):<p>Your first Z is waiting in chat.</p>}</article><article className="v-card"><h2>Your rewards</h2>{me.redemptions.length?me.redemptions.map(r=><div className="v-feed" key={r.id}><div><strong>{r.title}</strong><p>{r.status}</p></div><span>{z(r.cost)}</span></div>):<p>You haven’t redeemed a reward yet.</p>}<h2>BotRix conversions</h2>{cfg.botrix_enabled?<form onSubmit={e=>{e.preventDefault();act({action:'convert',points:Number(new FormData(e.currentTarget).get('points')),requestId:crypto.randomUUID()},'Conversion ticket submitted for review.');}}><p>{z(cfg.botrix_points_per_z).replace(/ Zs?$/, '')} BotRix points → 1 Z.</p><label>BotRix points<input name="points" type="number" min={cfg.botrix_points_per_z} step={cfg.botrix_points_per_z} required/></label><button disabled={busy}>Submit ticket</button></form>:<p>Conversions aren’t open yet. Keep using your BotRix points as usual.</p>}{me.tickets.map(t=><p key={t.id}>{t.points} points → {z(t.zs)} · {t.status}</p>)}</article></section></>)}
 {data&&tab==='Controls'&&me?.isAdmin&&<Controls onChange={load}/>}
 <footer className="v-footer"><span>ZEEKFUSION · THE Z MARKET</span><span>Earned in the moment. Kept in the Market.</span></footer></main></div>;
}
function Controls({onChange}){
 const [a,setA]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[selectedReward,setSelectedReward]=useState(null),[selectedQuestion,setSelectedQuestion]=useState(null);
 const reload=useCallback(async()=>{const r=await fetch('/api/z?admin=1');const j=await r.json();if(!r.ok)throw new Error(j.error);setA(j);},[]);
 useEffect(()=>{reload().catch(e=>setMsg(e.message));},[reload]);
 async function save(body){setBusy(true);setMsg('');try{const j=await request(body);setMsg(j.result?.username?`Winner: @${j.result.username}`:'Saved.');await reload();await onChange();}catch(e){setMsg(e.message);}finally{setBusy(false);}}
 function form(e,action){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));save({action,...f});}
 if(!a)return <p>{msg||'Loading your controls…'}</p>;
 const labels={question_z:'Question winner · Zs',question_interval_minutes:'Minutes between questions',answer_seconds:'Seconds to answer',botrix_points_per_z:'BotRix points for 1 Z'};
 return <div className="v-controls"><div className="v-card"><div className="v-row"><div><h2>Your stream, your rules.</h2><p>Rates apply to new earnings. Existing balances stay the same.</p></div><a className="v-button v-primary" href="/api/kick/login?bot=1">{a.botConnected?'Reconnect Kick bot':'Activate Kick bot'} ↗</a></div><p>{a.botConnected?'Kick bot connected.':'Connect the ZeekFusion Kick account to let the bot post questions and balance replies.'} Last timer check: {date(a.runtime.checked_at)}</p>{a.runtime.bot_error&&<p role="alert" className="v-alert">{a.runtime.bot_error}</p>}<button disabled={busy} onClick={()=>save({action:'tick'})}>Check live status now</button>{msg&&<p className="v-alert" role="status">{msg}</p>}</div>
 <form className="v-card" key={JSON.stringify(a.settings)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),settings={};for(const k of Object.keys(labels))settings[k]=Number(f.get(k));for(const k of ['questions_enabled','botrix_enabled'])settings[k]=f.has(k);save({action:'settings',settings});}}><h2>Earning rates & timing</h2><div className="v-form-grid">{Object.entries(labels).map(([k,l])=><label key={k}>{l}<input name={k} defaultValue={a.settings[k]} type="number" step={k.endsWith('_z')?'0.01':'1'} min="0" required/></label>)}</div><div className="v-checks">{[['questions_enabled','Automatic questions while live'],['botrix_enabled','Accept BotRix conversion tickets']].map(([k,l])=><label key={k}><input type="checkbox" name={k} defaultChecked={a.settings[k]}/>{l}</label>)}</div><button className="v-primary" disabled={busy}>Save settings</button></form>
 <section className="v-grid"><form className="v-card" key={'q'+selectedQuestion?.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'question',id:selectedQuestion?.id,question:f.get('question'),answers:f.get('answers'),category:f.get('category'),enabled:f.has('enabled')});}}><h2>{selectedQuestion?'Edit question':'Add a question'}</h2><label>Question<textarea name="question" maxLength="260" defaultValue={selectedQuestion?.question||''} required/></label><label>Accepted answers · separate alternatives with |<input name="answers" defaultValue={selectedQuestion?.answers.join(' | ')||''} required/></label><label>Category<input name="category" defaultValue={selectedQuestion?.category||'Stream'}/></label><label className="v-check"><input type="checkbox" name="enabled" defaultChecked={selectedQuestion?.enabled??true}/>Enabled</label><button disabled={busy}>Save question</button>{selectedQuestion&&<button type="button" onClick={()=>setSelectedQuestion(null)}>New question</button>}<details><summary>{a.questions.length} questions in the bank</summary><div className="v-scroll">{a.questions.map(q=><button type="button" className="v-list-button" key={q.id} onClick={()=>setSelectedQuestion(q)}>{q.enabled?'●':'○'} {q.question}</button>)}</div></details></form>
 <form className="v-card" key={'r'+selectedReward?.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'reward',id:selectedReward?.id,title:f.get('title'),description:f.get('description'),cost:Number(f.get('cost')),stock:f.get('stock')===''?null:Number(f.get('stock')),enabled:f.has('enabled')});}}><h2>{selectedReward?'Edit reward':'Add a reward'}</h2><label>Title<input name="title" maxLength="80" defaultValue={selectedReward?.title||''} required/></label><label>Description<textarea name="description" defaultValue={selectedReward?.description||''}/></label><label>Cost in Zs<input name="cost" type="number" min="0.01" step="0.01" defaultValue={selectedReward?.cost||5} required/></label><label>Stock · blank for unlimited<input name="stock" type="number" min="0" step="1" defaultValue={selectedReward?.stock??''}/></label><label className="v-check"><input type="checkbox" name="enabled" defaultChecked={selectedReward?.enabled||false}/>Available to viewers</label><button disabled={busy}>Save reward</button>{selectedReward&&<button type="button" onClick={()=>setSelectedReward(null)}>New reward</button>}<details><summary>{a.rewards.length} rewards</summary>{a.rewards.map(r=><button type="button" className="v-list-button" key={r.id} onClick={()=>setSelectedReward(r)}>{r.enabled?'●':'○'} {r.title} · {z(r.cost)}</button>)}</details></form></section>
 <section className="v-grid"><article className="v-card"><h2>Reward requests</h2>{a.redemptions.length?a.redemptions.map(r=><div className="v-request" key={r.id}><strong>{r.title}</strong><p>Kick ID {r.kick_user_id} · {z(r.cost)} · {r.status}</p>{r.status==='pending'&&<><button disabled={busy} onClick={()=>save({action:'redemption',id:r.id,status:'fulfilled'})}>Mark fulfilled</button><button disabled={busy} onClick={()=>save({action:'redemption',id:r.id,status:'refunded'})}>Refund Zs</button></>}</div>):<p>No requests yet.</p>}</article><article className="v-card"><h2>BotRix tickets</h2><p>Deduct points in BotRix, then record the deduction here. Approving awards Zs; it does not deduct BotRix points automatically.</p>{a.tickets.length?a.tickets.map(t=><form className="v-request" key={t.id} onSubmit={e=>{e.preventDefault();save({action:'conversion',id:t.id,status:'approved',proof:new FormData(e.currentTarget).get('proof'),freeEarned:new FormData(e.currentTarget).has('freeEarned')});}}><strong>Kick ID {t.kick_user_id}</strong><p>{t.points} points → {z(t.zs)} · {t.status}</p>{t.status==='pending'&&<><label>Deduction confirmation<input name="proof" minLength="5" placeholder="Deducted in BotRix on…" required/></label><label className="v-check"><input name="freeEarned" type="checkbox" required/>I checked and deducted these BotRix points.</label><button disabled={busy}>Approve & award Zs</button><button type="button" disabled={busy} onClick={()=>save({action:'conversion',id:t.id,status:'rejected',proof:''})}>Reject</button></>}</form>):<p>No tickets yet.</p>}</article></section>
 <SocialConnections/><ManageZs onChange={onChange}/><section className="v-grid">
 <form className="v-card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'giveaway',title:f.get('title'),description:f.get('description'),closesAt:f.get('closesAt'),enabled:f.has('enabled')});}}><h2>Create a giveaway</h2><p>One entry per Kick account. Add the prize, eligibility, and rules in the description.</p><label>Title<input name="title" required/></label><label>Description & rules<textarea name="description" required/></label><label>Entries close<input name="closesAt" type="datetime-local" required/></label><label className="v-check"><input name="enabled" type="checkbox"/>Open entries immediately</label><button disabled={busy}>Create giveaway</button>{a.giveaways.map(g=><div className="v-request" key={g.id}><strong>{g.title}</strong><p>{g.status}{g.winner_username?` · Winner @${g.winner_username}`:''}</p>{g.status==='draft'&&<button type="button" disabled={busy||Date.parse(g.closes_at)<Date.now()} onClick={()=>save({action:'publish-giveaway',id:g.id})}>Open entries</button>}{g.status==='open'&&Date.parse(g.closes_at)<Date.now()&&<button type="button" disabled={busy} onClick={()=>{if(window.confirm(`Draw one winner for ${g.title}? This result will be final.`))save({action:'draw',id:g.id});}}>Draw winner</button>}</div>)}</form></section>
 {a.failures.length>0&&<article className="v-card"><h2>Chat delivery needs attention</h2><p>These messages were not confirmed. They are not automatically resent, to avoid duplicate posts.</p>{a.failures.map(f=><p key={f.id}>{f.content} · {f.status}</p>)}</article>}<details className="v-card"><summary>Recent owner actions</summary>{a.log.map(l=><p key={l.id}>{date(l.created_at)} · {l.action}</p>)}</details></div>;
}
