import crypto from 'node:crypto';
import {db,rpc} from '../server/db.mjs';
import {requireAdmin,sameOrigin,apiError,seal,unseal,setCookie,cookie,site} from '../server/auth.mjs';
import {providers,authorize,exchange,refresh,account,videoPage,redirect} from '../server/social.mjs';
export const config={maxDuration:60};
const bad=message=>Object.assign(new Error(message),{status:400});
async function sync(platform){const lease=crypto.randomUUID();const row=await rpc('z_claim_social',{p_platform:platform,p_lease:lease});if(!row)return {done:true,busy:true};try{let token=await refresh(platform,unseal(row.app_cipher),unseal(row.token_cipher));await db('z_social_connections?platform=eq.'+platform+'&lease=eq.'+lease,{method:'PATCH',body:{token_cipher:seal(token)}});const a=token.account;const page=await videoPage(platform,token,a,row.cursor);if(page.cursor&&JSON.stringify(page.cursor)===JSON.stringify(row.cursor))throw bad('The platform repeated a page. Try syncing again later.');const saved=await rpc('z_finish_social',{p_platform:platform,p_lease:lease,p_clips:page.clips,p_cursor:page.cursor,p_token:seal(token)});return {done:!page.cursor,count:page.clips.length,saved};}catch(e){await db(`z_social_connections?platform=eq.${platform}&lease=eq.${lease}`,{method:'PATCH',body:{error:'Could not sync this account. Check app access, then reconnect and retry.',lease:null,lease_until:null}});throw e;}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{
 const q=req.query||{};
 if(q.job==='sync'&&req.method==='POST'){const token=req.headers['x-clips-tick'];if(typeof token!=='string'||!/^[-a-f0-9]{36}$/.test(token)||!await rpc('z_consume_social_tick',{p_token:token}))return res.status(401).end();const rows=await db('z_social_connections?token_cipher=not.is.null&select=platform,cursor,last_sync');const results=await Promise.allSettled(rows.filter(r=>r.cursor||!r.last_sync||Date.now()-Date.parse(r.last_sync)>21600000).map(r=>sync(r.platform)));return res.json({ok:results.every(r=>r.status==='fulfilled')});}
 if(q.callback){await requireAdmin(req);const p=q.callback;const raw=cookie(req,'z_social_oauth');if(!raw)throw bad('Connection expired. Start again from Controls.');const state=unseal(raw);setCookie(res,'z_social_oauth','',0);if(!providers.includes(p)||state.platform!==p||state.state!==q.state||state.expires<Date.now())throw bad('Connection expired. Start again from Controls.');if(q.error||!q.code)throw bad('Account connection was not approved.');const row=(await db('z_social_connections?platform=eq.'+p))[0];const token=await exchange(p,unseal(row.app_cipher),q.code);token.account=await account(p,token);await db('z_social_connections?platform=eq.'+p,{method:'PATCH',body:{token_cipher:seal(token),account:token.account.name,cursor:null,generation:null,last_sync:null,error:null,lease:null,lease_until:null}});return res.redirect(303,site()+'/#/vault?connections=1');}
 if(q.admin==='1'){await requireAdmin(req);const rows=await db('z_social_connections');return res.json({connections:rows.map(r=>({platform:r.platform,configured:!!r.app_cipher,connected:!!r.token_cipher,account:r.account,lastSync:r.last_sync,syncing:!!r.cursor,error:r.error,callback:redirect(r.platform)}))});}
 if(req.method==='GET'){const platform=q.platform||'all',sort=q.sort||'popular',offset=Number(q.offset||0);if(!['all',...providers].includes(platform)||!['popular','latest'].includes(sort)||!Number.isSafeInteger(offset)||offset<0||offset>1000000)throw bad('Invalid gallery filter.');const [clips,status]=await Promise.all([db('z_clips?select=id,platform,title,url,thumbnail,views,published_at&limit=24&offset='+offset+(platform==='all'?'':'&platform=eq.'+platform)+(sort==='popular'?'&views=gt.10000&order=views.desc,platform.asc,id.asc':'&order=published_at.desc.nullslast,platform.asc,id.asc')),db('z_social_connections?select=platform,last_sync')]);res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=300');return res.json({clips,hasMore:clips.length===24,status});}
 if(req.method!=='POST')return res.status(405).end();sameOrigin(req);await requireAdmin(req);const b=typeof req.body==='string'?JSON.parse(req.body):req.body||{};if(!providers.includes(b.platform))throw bad('Choose a platform.');const p=b.platform;
 if(b.action==='configure'){if(typeof b.clientId!=='string'||!b.clientId.trim()||b.clientId.length>500||typeof b.clientSecret!=='string'||b.clientSecret.length<8||b.clientSecret.length>1000)throw bad('Enter the app client ID and secret.');await db('z_social_connections?platform=eq.'+p,{method:'PATCH',body:{app_cipher:seal({id:b.clientId.trim(),secret:b.clientSecret.trim()})}});return res.json({ok:true});}
 if(b.action==='connect'){const row=(await db('z_social_connections?platform=eq.'+p))[0];if(!row.app_cipher)throw bad('Set up the developer app first.');const state=crypto.randomBytes(32).toString('base64url');setCookie(res,'z_social_oauth',seal({state,platform:p,expires:Date.now()+600000}),600);return res.json({url:authorize(p,unseal(row.app_cipher),state)});}
 if(b.action==='sync')return res.json(await sync(p));
 throw bad('Unknown action.');
 }catch(e){return apiError(res,e);}}
