import crypto from 'node:crypto';
import {db,rpc} from '../server/db.mjs';
import {requireAdmin,sameOrigin,apiError,session} from '../server/auth.mjs';
import {validateQuery,bodyObject,limit,invalid} from '../server/security.mjs';
import {editContent} from '../server/content.mjs';
import {appAccess,kickGet} from '../server/kick.mjs';
import {BROADCASTER} from '../server/domain.mjs';
export const config={api:{bodyParser:{sizeLimit:'16kb'}},maxDuration:30};
async function liveStatus(){let row=(await db('z_runtime?id=eq.1&select=is_live,checked_at'))[0];if(!row?.checked_at||Date.now()-Date.parse(row.checked_at)>60000){const owner=crypto.randomUUID();if(await rpc('z_lock',{p_name:'homepage-live',p_owner:owner,p_seconds:25})){try{const channel=(await kickGet('channels?slug=zeekfusion',await appAccess())).data?.[0];if(Number(channel?.broadcaster_user_id)!==BROADCASTER||typeof channel?.stream?.is_live!=='boolean')throw Error();row={is_live:channel.stream.is_live,checked_at:new Date().toISOString()};await db('z_runtime?id=eq.1',{method:'PATCH',body:row});}catch{ /* A stale status must not claim the streamer is offline. */ }finally{await rpc('z_unlock',{p_name:'homepage-live',p_owner:owner});}}}const fresh=row?.checked_at&&Date.now()-Date.parse(row.checked_at)<120000;return {status:fresh?(row.is_live?'live':'offline'):'unknown',checkedAt:row?.checked_at||null};}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{validateQuery(req);if(req.method==='GET'){if(req.query.access==='1'||req.query.adminPage==='1'){await limit(req,'owner-access',120);const user=await session(req);const isOwner=Number(user?.kick_user_id)===BROADCASTER;if(req.query.adminPage==='1')return res.redirect(302,isOwner?'/#/admin':'/');return res.json({isOwner});}if(req.query.admin==='1'){await requireAdmin(req);return res.json((await db('z_site_content?id=eq.1&select=content,revision,updated_at'))[0]);}await limit(req,'site-read',120);if(req.query.live==='1')return res.json(await liveStatus());const row=(await db('z_site_content?id=eq.1&select=content,revision'))[0];if(!row)throw Error();return res.json(row);}if(req.method!=='POST')return res.status(405).end();sameOrigin(req);const admin=await requireAdmin(req);await limit(req,'site-edit',30,60,admin.kick_user_id);const b=bodyObject(req),row=(await db('z_site_content?id=eq.1&select=content,revision'))[0];if(b.revision!==row.revision)throw invalid('Content changed in another window. Reload before saving.',409);const content=editContent(row.content,b);const result=await rpc('z_save_site_content',{p_actor:admin.kick_user_id,p_revision:b.revision,p_content:content});if(!result)throw invalid('Content changed in another window. Reload before saving.',409);return res.json(result);}catch(e){return apiError(res,e);}}
